### ISSUE TITLE
Seer accidentally contacting safe after death

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#10]
_Issue by **[kholerabbi](https://github.com/kholerabbi)** from 2014-01-19 10:53:48 UTC_
_Originally opened as https://github.com/lykoss/lykos-next-old/issues/9_

----

### The problem
After they `see` a villager, the seer may choose to PM the villager to tell them that they're safe. However, if night ends immediately and the seer is killed, then it's a common issue that the seer will PM their safe after death.

This is against the rules but happens by accident all the time, simply because the seer may rush to inform their safe, not realising that they have died.

### The solution
Players who use clients (such as irssi) that support a split notification window are able to see that they have died without switching back to the main channel—but many players don't have this option.

My suggested solution is to have lykos notify the seer that they have died, so that the seer does not have to switch back to the main channel before contacting their safe.

Furthermore, more often than not, I suspect this situation is due to the seer being the last night role to take action. In this case, lykos knows in advance that the seer is going to die and could customise the message. Indeed, lykos could choose *not* to inform the seer at all (e.g. “Sorry, you died before you managed to complete your vision”) which, although the safest option, might remove some of the fun as they continue to observe the game.

I've been playing this game off and on for a couple of years, and this has always been a problem. So it would be very nice to at least try to see if we can find a solution.

**Comment by jacob1** [comment]
is this still an issue? There are so many roles acting at night now, and small games are so rare, that it doesn't seem to happen very often, if at all.

If it is an issue, I recommend adding a check when seer sees, which calls a new function that checks if night ended (everyone acted), and in that case just append a small message to the results of their see. Which is basically what I suggested last time, just more specific now.

**Comment by skizzerz** [comment]
I personally don't think we need any technical changes for this, as anything we do won't actually fully "fix" the issue at hand here. Consider that seer sees, gets result, and wolf kills 0.5s after the result comes in. The fix proposed by jacob won't do anything in that case, and the seer can still pm after death. Hell, they can do that even if the wolf kills 30s after they see and they're being lazy/cheaty. Implementing technical solutions for social issues works some of the time, but this is not one of those times. The best solution I can think of is for people to be cognizant of the fact that something might slip in a split second after death, and if so they should avoid reading that message until after the game is over.

I recommend closing this issue out for real.
