### ISSUE TITLE
Make it so lykos can't troll voters

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#100]
Due to the way the voting system works, it is still possible for the bot to pick game modes that were not explicitly voted for. It makes far more sense that once people have voted for modes that only the modes voted for will show up.

Topics to consider for discussion:
* Do we want it so that we need a critical mass of votes (say 20% of players having voted for a gamemode) before we exclude modes not voted for?
* Do we want to adjust the "special" modes so that it only needs half of the voters to vote for it rather than half of the total players?

My personal opinion is no and yes, respectively, as I believe that will encourage more participation in voting for game modes if you literally count for nothing at all if you don't vote.

**Comment by jacob1** [comment]
Just my opinion (which a lot of people seem to disagree with :P):

I rarely use !game unless i'm helping to get a majority vote on some roleset. I like having it mostly pick them all with the frequencies given in the source, but people can increase the chances of a certain one if they want. I feel like if we do this; some less popular rolesets might almost never be picked. classic and mad are the rolesets voted for the least (even less than any of the 4 hidden rolesets), I see more votes for those two than I thought I remembered in the logs at least.

So i'd say if we did do this (>:), then it would be yes for 1 and no for 2.

Also might as well post it somewhere, I searched the logs and got these counts for number of times people have voted on rolesets:
default - 702
foolish - 642
drunkfire - 405
aleatoire - 360
rapidfire - 268
noreveal - 243
lycan - 215
amnesia - 203
alpha - 171
mad - 157
classic - 142

**Comment by jacob1** [comment]
More things mentioned in ##werewolf:
1) A lot of people want it to pick default if none of the rolesets get a majority. Dunno if total majority, or a majority of the people who actually used !game. Probably the second.
2) I suggested removing !game as a semi-serious joke :P

**Comment by ilbelkyr** [comment]
> I suggested removing !game as a semi-serious joke :P

I think it's a good idea to allow people to play what they *want* to play.

> I feel like if we do this; some less popular rolesets might almost never be picked.

I don't see why we'd force something onto people they don't wish to play. More variety is a good thing, but not if it's at the price of players actually enjoying the game.

**Comment by nyuszika7h** [comment]
@skizzerz @ilbelkyr :+1:

**Comment by jacob1** [comment]
ishanyx suggested in ##werewolf that maybe doing !game random would vote for a random roleset. If 'random' was picked, then it would just pick a roleset using the default probabilities. I think this makes more sense than having !game add to the default probabilities, and then unless someone did !game random it would pick from what people have already voted. If I code this might make some minor adjustments :P

**Comment by skizzerz** [comment]
Closing for now, nobody has contributed to this discussion for quite some time.

**Comment by nyuszika7h** [comment]
(Also, there is a `random` game mode now so even if we implemented isha's suggestion, it would need to be changed.)
