### ISSUE TITLE
Add !help for roles

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#105]
Going to the wiki is more tedious/distracting than a !command to get help on a particular role; I don't know if we need to duplicate the entire wiki entry but wouldn't hurt if we did...

**Comment by ChiyoOsaka** [comment]
I agree. Maybe we should add !role? I would like to work on something like that.

**Comment by Vgr255** [comment]
We could possibly use something like `urllib.request` to access the wiki directly, instead of duplicating it.
