### ISSUE TITLE
!help ignores !notice

### ISSUE THREAD

**Issue by ChiyoOsaka** [lykoss/lykos#107]
> (in /msg) [06:29:55 P] <Chiyo> !notice
> (a notice) [06:29:56 P] -lykos- Gameplay interactions will now use PRIVMSG for you. 
> (in /msg) [06:29:58 P] <Chiyo> help
> (a notice) [06:29:58 P] -lykos- Commands: admins, ....

**Comment by nyuszika7h** [comment]
This was supposed to be fixed already (#64). I blame @Vgr255 :P
