### ISSUE TITLE
Make stasis check both time and amount of games.

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#111]
An idea that came up in Esper's #Werewolf was to make stasis look for amount of time elapsed since the game that applied stasis, since fewer games are played than on freenode, and so people who get stasised in a game might need to wait a large amount of time before being unstasised, or to have an admin manually remove their stasis (what we do) after some time being stasised.

**Comment by nyuszika7h** [comment]
How should we determine the time that has to pass with no games played for one stasis unit to clear? Maybe it should be configurable? But what would be a sane default?

**Comment by Vgr255** [comment]
I think that one hour per game in stasis would be fine. Of course this would be a setting (eg. `GAME_STASIS_TIME = 3600`). I assume that, after one hour, games would have been played, and stasis elapsed long ago. Also, it could be a separate, per-leave setting (like `LEAVE_STASIS_TIME = 3600`) which could then be altered for each and not become insane if it's 10 games for example.

**Comment by nyuszika7h** [comment]
I think we have agreed that one hour is fine, now someone just needs to actually implement it.

**Comment by skizzerz** [comment]
This has now been done.
