### ISSUE TITLE
ghost's alignment in !revealroles is unclear

### ISSUE THREAD

**Issue by ishanyx** [lykoss/lykos#117]
05 141013 [freenode] -lykos(lykos@unaffiliated/nyuszika7h/bot/lykos)- wolf: mikicat | traitor: rika | amnesiac: NeoMahler (will become vengeful ghost) | seer: Axew | shaman: t0fu|work (gave retribution totem to NeoMahler) | villager: Dabo, Vgr | cursed villager: t0fu|work | dead vengeful ghost: bcode (villagers)

In this game bcode died of an exploding gun and was therefore on wolfteam, against village. If I hadn't known exploding guns counted as being killed by villagers, I would have assumed this listing was saying he was on the village team. The other status notes are much clearer. It should probably say something like (against villagers) here to remove the ambiguity.

**Comment by jacob1** [comment]
fixed in 8eef082067df871e66684eb8d446793fa3508c08
