### ISSUE TITLE
Dank memer, redneck

### ISSUE THREAD

**Issue by Cydrobolt** [lykoss/lykos#123]
Add two roles:
 - Dank memer
   - A dank memer will receive a bullet for winning the dank memes competition if he or she sends a dank meme during the nighttime. 
   - Dank memer wins with village. 

 - Redneck
   - A redneck has 3 bullets, with a low 40% accuracy. If the redneck is picked by a wolf while he has bullets, there is a 50% chance that the redneck will kill the wolf and survive. 
   - A redneck wins with the village.

**Comment by ilbelkyr** [comment]
I'm tempted to close this issue for being a joke ('dank memer', seriously?), but altered gunners might *possibly* happen in some mode.

I'm not sure we really need another gunner role for that, though...

**Comment by jacob1** [comment]
accuracy can already be modified by game mode, if we wanted we could just add a setting for a chance of gunner surviving when shooting wolf. I also don't think its different enough to require a new role >_>, but if it was a new role it should be a template "redneck gunner" kind of like sharpshooter
