### ISSUE TITLE
lykos doesn't join channels.

### ISSUE THREAD

**Issue by Agent-Isai** [lykoss/lykos#134]
For some reason, lykos doesn't join the channels that are specified in the configuration. I think since channels start with a hashtag, python thinks you're leaving a comment or something and ignores everything after the hashtag. Can you fix this (if it is a bug) or am I just experiencing this problem for some reason?

**Comment by skizzerz** [comment]
Channel names need to be in quotes, since they're strings.

Correct:
```python
CHANNEL = "##werewolf"
```

Incorrect:
```python
CHANNEL = ##werewolf-optest
```

**Comment by Agent-Isai** [comment]
I know, the name of the channel I put is in quotes, yet python ignores that.

**Comment by ilbelkyr** [comment]
Please provide relevant parts of the configuration as well as version information for the ircd used, or we won't be able to reproduce this.

**Comment by Vgr255** [comment]
Please also give us the output of `sys.version`

**Comment by ilbelkyr** [comment]
Marking as invalid as no-one else has been able to reproduce this, so it sounds like a mistake in the configuration file. (We might possibly reconsider that when @Agent-Isai provides details, but for now that seems the most likely issue.)

**Comment by Agent-Isai** [comment]
Sorry I haven't replied. Anyway, I'm running InspIRCd on Debian Jessie (8) and the following is my configuration (note: I have removed things like admin cloaks the nickserv password which shouldn't affect it)

<div>
PASS = "password"
CHANNEL = "#werewolf"
HOST = "localhost"
PORT = 6697
USERNAME = ""  # for authentication, can be left blank if same as NICK
NICK = "Wolf"
IDENT = NICK
REALNAME = NICK
CMD_CHAR = "!"
CHANGING_HOST_QUIT_MESSAGE = "Changing host"

SASL_AUTHENTICATION = True  # put account name in USERNAME ^ if different from nick
USE_SSL = True
DISABLE_DEBUG_MODE = False  # Entirely disable debug mode
IGNORE_HIDDEN_COMMANDS = True # Ignore commands sent to @#channel or +#channel
ALLOW_NOTICE_COMMANDS = False  # allow /notice #channel !command to be interpreted as a command
ALLOW_PRIVATE_NOTICE_COMMANDS = True  # allow !command's from /notice (Private)

ALLOWED_NORMAL_MODE_COMMANDS = []  # debug mode commands to be allowed in normal mode

OWNERS = ("network/staff/Owner",)  # the comma is required at the end if there is one owner
ADMINS = ("network/staff/Admin",)  # glob syntax supported (wildcards)

OWNERS_ACCOUNTS = ("Owner",)
ADMINS_ACCOUNTS = ("Admin",)

ALT_CHANNELS = ""

ALLOWED_ALT_CHANNELS_COMMANDS = []

USE_UTC = True # if True, will use the UTC time, else the local time
# {tzname} and {tzoffset} can both be used; respectively the timezone name (like UTC) and offset in the form +0000
# %Y is the year with century, %y is the year without, %m is the month, %d the day, %H hour, %M minute and %S seconds
TIMESTAMP_FORMAT = "[%Y-%m-%d %H:%M:%S{tzoffset}]"

# If enabled and DEV_CHANNEL is set, the bot will post tracebacks there.
PASTEBIN_ERRORS = False

# Channel(s) where errors will be sent to. Can be prefixed with '+' or '@' for sending to only voices or ops.
DEV_CHANNEL = ""
</div>

**Comment by ilbelkyr** [comment]
Can you run something like `LIST #werewolf` and report back the actual capitalization the ircd uses? I think lykos has had issues with that in the past. If it's `#Werewolf`, it needs to be that way in the config, too.

**Comment by Vgr255** [comment]
Capitalization will not, however, prevent the bot from joining the channel. Please run the bot with the `--verbose` option or add `VERBOSE_MODE = True` to the config and pastebin all the output. You may strip out SASL auth and motd, but don't strip out anything else.
