### ISSUE TITLE
Advertise `!pingif`

### ISSUE THREAD

**Issue by zamabe** [lykoss/lykos#138]
The only way I knew about `!pingif` was the deprecation message. Being opt-in with no advertising means less utility/use.

There should probably be a message in a relevant place among the game events, such as being done in addition to the first `!pingif` generated ping so as to provide information, especially to newer users, that it exists and that they have to opt-in to said feature.

**Comment by nyuszika7h** [comment]
What do you mean by "first `!pingif` generated ping"?

**Comment by zamabe** [comment]
"PING!-3 Players..."

**Comment by nyuszika7h** [comment]
You mean the first ping for each new game?

That wouldn't help at all, as we already put `!pingif` in the topic **and** it's mentioned whenever someone does `!ping`. The people who are pinged by `!pingif` already know about it, and those who don't won't suddenly notice it if they haven't noticed the topic or the `!ping` notice yet.

**Comment by zamabe** [comment]
Both of the messages you and I have referred to are **deprecation messages**. They are, by definition (hopefully), temporary.

As for the one in the topic, exactly how is that meaningful. Sure you can tell people they're stupid for not reading the topic, but frankly _basically no one_ reads the topic. ##werewolf is quite an active channel, so the giant topic message is lost rather quickly.

Adding an advertisement to a PING about why these people are being selectively pinged serves to offer rather constant advertisement which is very easily ignored but which does provide the information at the time when it is most relevant.

**Comment by skizzerz** [comment]
If someone is curious as to why people are being pinged by the bot, they can ask and I'm sure someone would be more than happy to tell them about !pingif. While adding an advertisement for new players may be helpful, adding it to !pingif is **not** the appropriate location for it; it will only serve to annoy current players and help pretty much nobody.

**Comment by zamabe** [comment]
I'm sure someone would be more than happy to tell them about !pingif.

I don't disagree with this statement, but it assumes that this kind of person would always be around.. The point is to not encourage a verbal knowledgebase, though. Perhaps a `!wiki` entry would be more appropriate?

**Comment by zamabe** [comment]
> I'm sure someone would be more than happy to tell them about !pingif.

I don't disagree with this statement, but it assumes that this kind of person would always be around. The point, though, is the opposite of a "verbal" knowledgebase.

> While adding an advertisement for new players may be helpful, adding it to !pingif is not the appropriate location for it

Advertising this feature at the event that it causes best correlates the feature with an example of its usefulness.

> it will only serve to annoy current players and help pretty much nobody.

I highly doubt your value proposition evaluation; it is questionable at best. I think you think of current players as extremely sensitive. To give a counter-example: `!stats`. It is a far more annoying feature in that it is a false alert which pings everyone yet is not actually a thing they need to be alerted for and provides no information to them (the unnecessary ping bit of the command) multiple times during the actual game play, yet very few people are annoyed by its existence. The opposite is the case in almost every way for advertising `!pingif` as suggested. It pings no one and is not a false alert; and it shows up exactly once and never during game play. I have no idea where you see this as being unacceptably annoying.

**Comment by Vgr255** [comment]
Is this still relevant? This command is no different than most others, and I don't think any such feature (however awesome it may be) would deserve to be advertised as such. I mean, `!wiki` is super mega useful, yet has absolutely nothing that showcases it other than people doing `!help` and trying random commands, or people who already know about it and use it.
