### ISSUE TITLE
Stats Page

### ISSUE THREAD

**Issue by jztech101** [lykoss/lykos#144]
a stats page like https://cajs.co.uk/stats/esper/techcavern.html - but it shows the people who played the most amount of games and when they were most active.

**Comment by jacob1** [comment]
Uh, we already have http://wolf.xnrand.com/stats/

If you scroll down there is a section called "Lykos Statistics" which lists some ##werewolf specific stuff. Unfortunately it is broken (the idle stats work though). Maybe this issue can be repurposed for fixing the stats or adding more?

Here is the source of the pisg I use to generate those: https://github.com/jacob1/pisg

**Comment by ilbelkyr** [comment]
That said, I'm in favor of collecting some more stats in the bot's database. Scraping logs for that seems like a strange way to go about things when the bot could collect the data directly.

**Comment by jztech101** [comment]
@jacob1 um. the lykos stats doesn't really show much. Also, the daily statistics up is very confusing. But what I mean is what times people tend to play games, and how many player games? Also, preferably a visual kinda thing for what is currently !p?

**Comment by skizzerz** [comment]
The bot does not (and will not) have a webserver component; if someone wants to make use of the stats db to populate a web page, that's on them and belongs in a different project. If something official was made in that regard, it would be in a repo called lykos-stats or something, not here.

If you have requests for additional stats tracking to support such a webpage, please open new issues about those things.
