### ISSUE TITLE
Hilight people only for ping

### ISSUE THREAD

**Issue by hax404** [lykoss/lykos#148]
I don't want to be hilighted when someone types !stats or something else. In my opinion lykos should insert ZERO WIDTH NO-BREAK SPACE after first char of Nick. So everyone knows who was mentioned and the player itself is not hilighted. For example this is already implemented in another irc-bot [1].

[1] https://github.com/raumzeitlabor/raumzeitstatus/commit/06a8bf0a9745ae1db8292bd0564b5c9cb1b9d697

**Comment by ilbelkyr** [comment]
Pinging players tends to be an intended effect of using `!stats`, though. Most blatantly, with role reveal turned off, that's basically all it does.

Lead safes rely on that to poke other safes who haven't seen their claim yet. Ideally we wouldn't need to ping people for that, but sometimes we do :/

**Comment by skizzerz** [comment]
!stats highlighting people is an intentional feature, not a bug.

**Comment by nyuszika7h** [comment]
Thanks, you beat me to the wontfix.
