### ISSUE TITLE
Add alternate retract command

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#153]
During night, one may type !vote to vote to lynch someone; in addition, one may also type !v.

[20:29:13]  <+mj94>	!v 2
[20:29:13]  <@wolfbot>	mj94 votes for 2.

When retracting a vote, one may type !retract, but !r does not work.

[20:34:21]  <+mj94>	!r
[20:34:24]  <+mj94>	!retract
[20:34:24]  <@wolfbot>	mj94's vote was retracted.

I suggest implementing !r as an alias for !retract for ease of use similar to commands we already have.

**Comment by Asorailahd** [comment]
I approve of this idea wholeheartedly. It needs to happen yesterday.

**Comment by skizzerz** [comment]
Added in 0286a55e6b0f4e15662169ee9b06c6ff034c64a6
