### ISSUE TITLE
Ping-if handling broken (on InspIRCd?)

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#155]
As reported by mon_ in -dev (and in https://gist.github.com/anonymous/9373cd68d8d8ea0cf544), it seems that people who didn't set their preferences get pinged even. I think this may be related to the shenanigans we do with `DISABLE_ACCOUNTS` but I can't get further. It does so even with an empty database, so that can't possibly be the issue.

**Comment by unsangkarable** [comment]
Additional notes:

1) Every nick have different host.
2) eggBomb and eggRoullete have their own nickserv account .
3) egg eggCupid eggPisg eggQuote eggSearch eggSeen eggUNO eggWSI (logged in by using eggSeen nickserv account).
4) koeyti[A]w, mon, shaquille using own nickserv account.

**Comment by nyuszika7h** [comment]
Should be fixed by 3ce8568, but there is another issue reported by @MJ94 we haven't been able to reproduce – that is, the same people getting pinged multiple times.

**Comment by unsangkarable** [comment]
This issue is no longer reproducible on InspiRCd. This issue can be closed. Thanks for the fixes!
