### ISSUE TITLE
Send at most one GIF or fortune per night, after all deaths have been processed

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#156]
Currently, GIFs and fortunes have a random chance of triggering after every single death. This was never intended; it should only happen once at the end of night after all deaths have been processed.

**Comment by ilbelkyr** [comment]
Especially with fortunes, I'd say it's an unintended feature, not a bug.

nyuszika7h <notifications@github.com> schrieb am So., 9. Aug. 2015 18:30:

**Comment by nyuszika7h** [comment]
That's why I added the "cosmetic" label.

**Comment by nyuszika7h** [comment]
Never mind, you're right.

**Comment by Vgr255** [comment]
Regarding this issue, there are a few other things like this that need to be triggered only once (devoicing comes to mind). I'm thinking of either 1. adding a new function (or generator, or anything) that can process those all at once, or 2. just group them. I have a very specific idea about how to go with this, so I can probably do this when I'm back home.

**Comment by skizzerz** [comment]
This has been the case for a while now, closing.
