### ISSUE TITLE
Players Not Identified to NickServ after !frestart

### ISSUE THREAD

**Issue by AlphaT3ch** [lykoss/lykos#158]
If you try any commands like "!p" after a frestart, the bot thinks you aren't connected to NickServ. I had to cycle the channel to make it work again.

**Comment by ishanyx** [comment]
When, where and under what conditions did this happen? It's never happened to me on freenode.

**Comment by nyuszika7h** [comment]
I'm suspecting this is on InspIRCd. They don't support WHOX, therefore unfortunately there is no plausible way for us to fix this.

**Comment by nyuszika7h** [comment]
Related: #112

**Comment by AlphaT3ch** [comment]
The issue has seemed to be fixed with the new pull

**Comment by nyuszika7h** [comment]
I doubt it was magically fixed, are you sure the player you tested it on didn't join **after** the bot?

**Comment by skizzerz** [comment]
"Fixed" in 75c407c403f7457ccbd420c1e986c5641f610907 by removing account tracking entirely for ircds without whox support; it now tracks player stats by nick so !p works regardless.
