### ISSUE TITLE
Lykos no longer devoices dead players if overnight devoicing is enabled

### ISSUE THREAD

**Issue by laneatomic** [lykoss/lykos#160]
The recent commit to allow for overnight devoicing looks to have broken devoicing people who are killed during the day (lynched, shot, timeout, etc.) and at day end. Players who are killed overnight stay devoiced properly. Additionally, the bot isn't devoicing people when a game start timer times out.

**Comment by Vgr255** [comment]
Oh. Day kills. Damned.

**Comment by jacob1** [comment]
closing, since this was already fixed in 279328296dfe088073e2983a5eb976ab3259acd0
