### ISSUE TITLE
Bot not recognizing PM commands without prefix on certain IRCds when using different case for nick than the bot uses

### ISSUE THREAD

**Issue by laneatomic** [lykoss/lykos#161]
We haven't been able to figure out why yet, but Lykos isn't recognizing commands (gameplay or !commands) when sent from Mibbit in a query. This has been repeatable by every user our group has had using Mibbit, and we have a large userbase that uses Mibbit to connect to our IRC network. Telling them to switch off of Mibbit onto a real client isn't always a viable solution.

**Comment by nyuszika7h** [comment]
That's definitely strange, I have no idea why it would only happen with Mibbit.

(But they should be using KiwiIRC instead anyway! :P)

**Comment by laneatomic** [comment]
haha yeah, it's strange. The best thing I can think of is that it doesn't send PRIVMSG the same way as other clients, and the bot isn't able to parse what it gets.

**Comment by jacob1** [comment]
You can run the bot in debug mode to see what it is getting. What network is this on? Maybe the network / mibbit is doing strange things

**Comment by nyuszika7h** [comment]
Please try with `./wolfbot.py --debug` and post the debug logs here.

**Comment by laneatomic** [comment]
@jacob1 irc.coldfront.net. I'll try running a clone in debug (I don't host the bot currently) and test tonight.

**Comment by jacob1** [comment]
I just tested it myself, it worked just fine (normal commands like coin, and 'see'). I also joined the network from mibbit and PMed your actual bot and it worked too. So i'm not sure what the issue could be :P

**Comment by laneatomic** [comment]
Specifically it looks like it's the widget version of Mibbit hosted at https://politicsandwar.com/irc/ that's having the issues. When I was testing with that widget, I was unable to replicate it myself. However, a few of the users are able to replicate it. I'm not getting any errors reporting from the bot itself. If I can replicate this, I'll update again, otherwise I'll just tell these mibbit users to not use a crappy client.

**Comment by skizzerz** [comment]
1) Please attach the debug log (aka the output of ./wolfbot.py --debug. Make sure to strip passwords out of it as it **will** contain the bot's nickserv password). Beyond the password, **do not omit anything from the log**, it should contain logs from when the bot was first started up until you decided to stop it. Only giving a small snippet of the log may adversely impact my ability to figure out what is going on.

2) Please let me know which user(s) are having issues. Ensure that they tried and failed while the bot is in debug mode (and therefore their tries are logged).

**Comment by laneatomic** [comment]
Debug output: https://gist.github.com/blindirc/6fd1e9e919b958f79b06

**Comment by laneatomic** [comment]
And now we're seeing it with users not on mibbit. Tacocat was the user this time. Full output from launch to stop.

https://gist.github.com/laneatomic/a4f7f7cbb8a8f50fd394

**Comment by ishanyx** [comment]
The ones that don't work have the bot's nick in all lowercase. It kind of looks like it's case sensitive for its own nick in /some/ incoming PMs, which never mattered anywhere else, but on unreal whatever case the sender typed is preserved instead of using the actual case of the target nick. I don't know why that would apply to 'kill' and not to '!help', though.

**Comment by nyuszika7h** [comment]
I'm going to fix this by properly lowercasing nicks on comparison everywhere.

**Comment by nyuszika7h** [comment]
Though I should probably just get this one fixed first, as there's a lot of corner cases for lowercasing to take care of, such as translating the nicks in the stats to lowercase.

**Comment by nyuszika7h** [comment]
This particular issue should be fixed; see #164 for more.
