### ISSUE TITLE
Lover wins when Fool is lynched

### ISSUE THREAD

**Issue by laneatomic** [lykoss/lykos#162]
When the fool was lynched, the lover/matchmaker won. I don't have debug logs, however here is the game over message to show. I will try replicating it with debug on to provide any logging I can.

```
17:56 Werewolf: Kyubey votes for Kyubey.
17:56 Werewolf: Despite protests, the mob drags their victim to the hanging tree. Kyubey succumbs to the will of the horde, and is hanged. The villagers have killed a fool.
17:56 Werewolf: Game over! The fool has been lynched, causing them to win.
17:56 Werewolf: Game lasted 04:21. 02:21 was day. 02:00 was night.
17:56 Werewolf: The werekitten was []. The warlock was Archangel. The seer was Roy_Mustang. The hunter was MoonPie. The doctor was justagirl. The matchmaker was Alataq[TLF]. The fool was Kyubey. The turncoat was Bet. The lycan was Isolatar. The lovers were Kyubey/Alataq[TLF].
17:56 Werewolf: The winner is Alataq[TLF].
```

**Comment by ilbelkyr** [comment]
Which game mode is this? 'random' changes that on purpose, IIRC.

**Comment by skizzerz** [comment]
@ilbelkyr: note how there is only 1 winner listed, and that winner is the fool's lover and not the fool itself. Random makes it so that the lover should win in addition to the fool, not instead of. There's definitely something funky going on here.

**Comment by laneatomic** [comment]
It is definitely random mode. I can't successfully replicate it using debug options. Also, I found that `!frole <nick> fool` does not work, no matter what combo I try.

**Comment by skizzerz** [comment]
`!frole` is only enabled while in debug mode. In any event this has been fixed, do a `!fpull` and `!frestart` to update the bot with the fix.

**Comment by laneatomic** [comment]
That was fast. :beers: mate!

**Comment by nyuszika7h** [comment]
Uh, this is not a bug? random sets `LOVER_WINS_WITH_FOOL` to True.

**Comment by nyuszika7h** [comment]
Oh wait, the actual fool didn't win...
