### ISSUE TITLE
Player list is sent twice for wolf-assassins

### ISSUE THREAD

**Issue by lutoma** [lykoss/lykos#174]
When both a wolf-character and an assassin, lykos seems to send the list of players twice, once for the wolf role (with wolfteam-aligned roles revealed), and once for assassin, without anything revealed.

That wall of text makes it really easy to miss the fact you're also assassin. Instead, it should probably only print the players with roles once after the other messages.

```
You are a hag. You can hex someone to prevent them from using any special powers they may have during the next day and night. Use "hex <nick>" to hex them. Only detectives can reveal your true identity, seers will see you as a regular villager.
Also, if you PM me, your message will be relayed to other wolves.
Players: banzaikitten, abra0, sapphire (wolf), m712, Pichu, fetergent (cursed traitor), maserati (wolf), Feeshee, AvatarFreak24, mellowcraze, michagogo (cursed), jacob1, nyuszika7h
You are an assassin. Choose a target with "target <nick>". If you die you will take out your target with you. If your target dies you may choose another one.
Players: AvatarFreak24, banzaikitten, Pichu, jacob1, m712, michagogo, maserati, Feeshee, abra0, nyuszika7h, sapphire, fetergent, mellowcraze
```

**Comment by jacob1** [comment]
I suggest turning on !simple, it might help clean up the text enough that you will notice what roles you are. Then if you don't know how a role works, you can use !wiki (but after enough games you understand it all)

The second list is slightly different, I don't know if it is that important to not print it twice. A lot of roles besides wolf technically have this problem anyway.

**Comment by Vgr255** [comment]
I will look into it, the way I have in mind will factor out some of transition_night

**Comment by skizzerz** [comment]
Do submit it as a PR though. I've gotten some more work done on roles.py yesterday and these instructions are now individually separated into their own classes and printed out as part of an event.

Doing what OP requested in the new roles classes will most likely be a WONTFIX unless there is some not horribly hacky way of going about it.

Another large part of the player listings is that they tell you the **valid** targets to choose from for that role/template. I'd like for that to be maintained in any eventual solution if possible.

**Comment by Fudster** [comment]
This should be closed. Fixed by #177

**Comment by skizzerz** [comment]
No it wasn't. That PR was not merged.

**Comment by skizzerz** [comment]
Closing as wontfix; this is really not possible with how role messages are sent out now, and trying to detect when a list can or cannot be merged is difficult. For example, an assassin dullahan would be sent two lists, but the assassin list would be everyone whereas the dullahan list would only be their targets. So, we need to have 2 lists in that case, whereas things like wolf assassin could be merged together.
