### ISSUE TITLE
Total wins are not displayed

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#175]
We only log team wins, and individual wins. This used to work just fine, but since matchmaker and all the new roles, neither of these really logs whether your name appeared in the end of game winners list, which is what people actually care about.

The problem with fixing this is that we don't currently have any stats on total wins. There are a few things we could possibly do:
1. Reset the rolestats table, possibly making a backup for people to view somewhere.
2. Just set total wins to be the highest of either individual or team wins for all players, and have it continue from there.
3. Create two more columns, one containing the number of games played since we added total wins logging.

2 would cause some stats to continue being slightly lower than they should be still (but would have the lowest effect on stats and still easy), and 3 is really weird and probably not a good idea. I don't know what option is best.

**Comment by laneatomic** [comment]
Considering both current and future uses: option 3 wouldn't be very useful for new bot users, as they would have 0 games before total wins logging. I'd definitely vote against 3. I would be okay with either 1 or 2 on our network, with 1 probably being preferred. It isn't the end of the world if stats get reset.

**Comment by MJ94** [comment]
I'm not too much of a fan totally resetting stats. I think it's fun to see what we've played over time.

**Comment by jacob1** [comment]
Looks like we chose option 1!

Now that total wins are properly stored, we need to actually display it ... it still only displays team and individual wins.

**Comment by Vgr255** [comment]
Seems to be fixed now!

**Comment by jacob1** [comment]
Well it's technically fixed, but it looks like I forgot to change the title to "Total wins are not displayed". !pstats should show your total wins, right now it still only displays individual and team wins (I think). I'll double check when I get on IRC.

**Comment by Vgr255** [comment]
Oops, my bad. It's apparently not displayed (I was confused with Total games). Reopening.

**Comment by skizzerz** [comment]
Fixed in 0c0268e
