### ISSUE TITLE
Use a more clear message for ambiguous game modes

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#176]
It might be nice if the bot said something like this:

```
-lykos- Ambiguous game mode: al. Possible game modes: aleatoire, alpha
```

**Comment by Fudster** [comment]
Which way would you prefer to do it then?

- list all game modes.
- list all *possible* game modes.

**Comment by nyuszika7h** [comment]
If it's a partial match, it should only list the possible ones. If there's no match, it *could* possibly list all game modes, or just tell you to use `!modes`.
