### ISSUE TITLE
Splitting messages out of code into configurable file

### ISSUE THREAD

**Issue by tacocatcodes** [lykoss/lykos#180]
Requirements:
- security - arbitrary files shouldn't be able to be read
- invalid keys shouldn't stop a game - they need to fail gracefully (preferably fall back to defaults)

Phase 1 Tasks:
- [x] Move all communicated messages (i.e. not logging) to `messages/<language>.json`
- [x] Load messages from file and call in place of hard-coded messages in wolfgame.py
- [x] Replace hard-coded messages in gamemodes.py

Phase 2 Tasks:
- [x] Create way to override/append additional custom messages (`custom/<language>.json`?)
- [ ] Load messages into language cache for all languages currently in use

Phase 3 Tasks:
- [ ] Allow users to select their own language

**Comment by Vgr255** [comment]
As someone who did i18n before, this is not an easy task. I have a half-finished framework for i18n which I can modify and incorporate into lykos. It even has partial test coverage! There's also a ton of different modules and packages available to do string interpolation. That's not "just an implementation detail" for those who might think so - knowing what framwork we're gonna be using is where such a project should begin. Unlike what most people think, the proper way to start is never to throw in random files then build a framework around it - you need to build the framework and make you file types around the framework. I suggest we start working on a framework for i18n (we can start by mine if you feel like it, it needs a few tweaks to run on 3.2 though), and then nothing stops up from adding in those files in the meantime (but we need to know where we're going, at least roughly, and not just dive in blindly).

**Comment by skizzerz** [comment]
Closing this out as the goal has largely been achieved; lykos is for the most part translatable now. Per-user language setting is unlikely to occur as all users need to be speaking the same language to do stuff in the channel anyway
