### ISSUE TITLE
Improvements to vote starting behaviour

### ISSUE THREAD

**Issue by lutoma** [lykoss/lykos#182]
The vote to start PR has been merged and so far, it seems to be working pretty well. At least I haven't witnessed any situations where people wanted to start and couldn't as a result of this behaviour.

Still, there are some annoyances left that I feel should be discussed and/or changed:
- The !start rate limiting can be pretty inhibiting now that calling the command doesn't immediately start the game. For example, if someone joins and tries to do !start after, they won't be able to as the wait timer is still on. If they try to do !start after the timer is over, they often won't be able to due to the rate-limit.
- The wait behaviour should be smarter. Right now, doing !w while someone has voted to start effectively blocks the starting of the game entirely: Nobody will be able to vote to start anymore for 30 seconds, and after 1 minute, the votes are reset. I think wait times should either only apply to the first !start vote (making it more similar to how it was before), or !w should have some different behaviour (someone suggested removing the votes, not sure about that). Or alternatively the start timeout could be increased by the wait time.
- I feel like the exact number of votes required to start the game still needs some tweaking. Not too sure about the exact numbers though.
- The start timeout of 1 minute is a bit too short. I think 2 minutes or at least 1:30 would be more reasonable. Also it should probably be configurable. Maybe game size should also influence the wait time.

I'd be willing to implement these if a consensus is found on what behaviours are desired/best.

**Comment by laneatomic** [comment]
>For example, if someone joins and tries to do !start after, they won't be able to as the wait timer is still on. If they try to do !start after the timer is over, they often won't be able to due to the rate-limit.

I think the wait timer should still be applicable, but I agree that the rate limiting should be adjusted. Perhaps only apply it to the first !start that kicks off voting? The only scenario I can think of that would depend on rate-limiting is people trying to spam !start during a !wait timeout.

> Or alternatively the start timeout could be increased by the wait time.
> The start timeout of 1 minute is a bit too short. I think 2 minutes or at least 1:30 would be more reasonable. Also it should probably be configurable. Maybe game size should also influence the wait time.

I could go both ways on this. I like that !wait is still effective during start voting. On our server we often wait on a few certain players (relatives of other players) to connect to IRC to join. Sometimes someone won't realize we're waiting for people to connect to the network and start the !start vote, after which another will !wait. OTOH, I do think we need a way to manually extend the start timeout. Perhaps a !waitvote command or something?

**Comment by jacob1** [comment]
I think only making the wait time apply to the first !start wouldn't be good, I always !wait when I see someone else trying to !start but before it has entirely gone through.


Anyway, maybe 1:30 would be better than 1:00, that also means you can't !wait twice to cancel the start unless someone else actually joined (maybe a good thing). But, I do like being able to cancel the start by doing waits.

# of votes needed to start the game seems fine to be, but I wouldn't mind adjustments.

**Comment by skizzerz** [comment]
Cleaning up old discussions. Since nothing happened here for years, I'm assuming things are good enough as-is. Re-open this issue if necessary.
