### ISSUE TITLE
!swap is sensitive to capitalization

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#184]
[20:59] <NotMJAtAll> swap mj94
[20:59] <lykos> That person is not playing.
[20:59] <NotMJAtAll> swap MJ94
[20:59] <lykos> You are a villager.

Lykos should support any nick capitalization, as other commands such as !lynch and !vote do.

**Comment by Vgr255** [comment]
You should probably just use a bare `swap`, it will work just fine. You should never have to specify a nickname.

This does _not_ mean, however, that this won't be fixed in the future. It's just low priority right now.
