### ISSUE TITLE
Pray does not narrow down suspects if used over two seperate nights

### ISSUE THREAD

**Issue by toagac** [lykoss/lykos#185]
If praying for one role on two separate nights, the bot does not narrow down the choices from the last night.

In the log below, I prayed once on both nights but presume it also applies to praying two separate roles over two nights.

The specific lines in question are 29 and 179
http://pastebin.com/Khv36DDS

**Comment by skizzerz** [comment]
Working as intended -- you only get one shot for a particular {person, role} combo. If you use it again on another night, it tells you if anyone else has that role, but never tells you the original person again.
