### ISSUE TITLE
alphabetizing role_order

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#187]
Currently, the end of game roles and !revealroles output are listed in the order defined in ROLE_GUIDE. This is mostly done by function, so first comes wolves, then village roles in some functional order, then neutrals, then templates. I think the two parts in the middle, the villagers and the neutrals, can be a bit hard to read and find what you are looking for at the end of the game, or in revealroles. They are sort of ordered by function, I notice seer type roles grouped together, guardian roles together, jester and fool together, and also they seem to be somewhat in order of power. But unless you memorize the order, the "order" isn't really that helpful.

I think it might be easier to find what you are looking for if the village section and the neutral section were ordered alphabetically. It used to be like this, back until we converted everything to sets. I thought I mentioned it should be changed to be more alphabetical back then, but I guess that never got done. It has been bothering me for a while that it is hard to find what i'm looking for in the end of game role list (happens often).

Sorting by function / power makes sense for ROLE_GUIDE itself, but when you only select a few of the roles for a game mode, the order just looks entirely random, meaning you have to memorize which roles go where (which I have done to an extent but not entirely).

I think the wolf ordering makes perfect sense at the moment, so that probably doesn't need to be alphabetized. Templates I guess could be alphabetized too but there are so few of them it doesn't really matter

**Comment by nyuszika7h** [comment]
Closing due to lack of interest. I've explained why I don't like this already.
