### ISSUE TITLE
Option to disable rate limits in debug mode

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#194]
This could be useful when debugging sometimes.

**Comment by Fudster** [comment]
If you still want this done. 

```         if not botconfig.DEBUG_MODE and botconfig.DISABLE_DEBUG_MODE_TIMERS: ```
Would do the trick no?

**Comment by skizzerz** [comment]
No, it needs to be a new setting.

**Comment by skizzerz** [comment]
Can be done with eval/exec so I'm not particularly interested in this, and it hasn't come up in literal years. Just going to close this out.
