### ISSUE TITLE
Lykos not responding to wild child `choose`

### ISSUE THREAD

**Issue by MJ94** [lykoss/lykos#223]
I was wild child in maelstrom today, and the bot didn't respond when I chose an idol.

>[21:39:18]  <lykos>	You are a wild child. You must pick an idol with "choose <nick>", and you will ?>become a wolf if your idol dies. You are a villager as long as your idol is alive.
>[21:39:30]  <MJ94>	choose mel
>[21:39:45]  <MJ94>	choose mellowcraze
>[21:40:23]  <MJ94>	choose mel
>[21:40:25]  <MJ94>	stats
>[21:40:26]  <lykos>	8 players: iovoid, Katfox, dwynwen_ddlleyw, mellowcraze, MJ94, sidnata, >Starman, Elesis

**Comment by Vgr255** [comment]
Wild child only works on n1, so maelstrom broke it. Blacklisting off maelstrom.
