### ISSUE TITLE
Sleepy bugs

### ISSUE THREAD

**Issue by Michagogo** [lykoss/lykos#234]
Just played [this game](https://www.irccloud.com/pastebin/xI3Inye4/bugged%20game%20-%20doomsayer%20didn't%20win) in sleepy mode, and the ending of the game bugged out.
- I turned to doomsayer, yet for some reason part of the bot thought I was dead, and so when everyone but me died at once in the last night (6 players, wolves and dullahan each killed 1, dullahan spine-whipped a 3rd, and then the vigilante killed the dullahan, dying in the process), it claimed that there were no more players remaining, rather than awarding me the win on behalf of wolfteam. I'm assuming here that doomsayer counts as a wolf for this purpose (and not like, say, a hag or sorcerer), because doomsayer gets the kill command (for voting on the wolfkill) in addition to their see command, and in addition, when it was just me and the traitor, I held the traitor back from turning.
- Also, the message says that there are no players remaining and that nobody wins, and then after the role listing it promptly states that the winner is the dullahan. I understand why that's happening, but it shouldn't say "nobody wins" unless that's actually true,

**Comment by skizzerz** [comment]
Can't repro this anymore, so I think it got fixed.
