### ISSUE TITLE
Static type checking: How far can we go?

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#239]
As an attempt to help mitigate the random issues we might have in the code, I've proposed that we start using type hints in functions everywhere. The idea is that we can run [MyPy](https://github.com/python/mypy) and hopefully fix some of the lingering issues that have never been addressed (and/or that we never knew of).

With [PEP 484](https://www.python.org/dev/peps/pep-0484/) accepted, Python 3.5 now has the [`typing`](https://github.com/python/typing) module as part of the standard library. The module is available as a third-party module all the way back to 3.2 with `pip install typing` (it also comes with MyPy). The `typing` module is pretty much required if we're to add type hints and use MyPy to do static type checking.

So, how far are we willing to go, and how much can we reasonably ask of the bot owners? A simple `pip install` doesn't sound too bad to me. Anyone has any opinion in the matter? Is there anything I've forgot?

Also, I'll start shortly to push type-hinted files to a separate branch. Maybe we could "tag" the pre-type-hint stage (i.e. before we merge it all in master) for users who don't want to use it (but that's just a random thought).

**Comment by nyuszika7h** [comment]
Sounds good to me, can also add a `requirements.txt` and ask people to do `pip install -r requirements.txt` to install this an any future dependencies.

**Comment by Vgr255** [comment]
+1 for `requirements.txt` instead, I forgot about that. Bit of a stretch, but maybe we could have lykos automatically do all of this on startup if the stuff isn't installed. For now it'd be `try: import typing; except ImportError: pip.install("typing")` or something like that. But then even `pip` isn't guaranteed to be included in Python < 3.4 ...

**Comment by nyuszika7h** [comment]
Also, if we tell users to run `pip`, we should probably tell them to use `python3 -m pip` as that's the most reliable cross-platform way instead of trying to figure out if it's `pip3` or `pip3.X` or `pip-3.X`.

**Comment by Vgr255** [comment]
On my machine it's `py -m pip` though, `python3` or `py3` don't even work. The recommended way should be `py -3 -m pip` instead. (This is also somewhat related to #172 ).

**Comment by nyuszika7h** [comment]
`py` is Windows-specific.

**Comment by Vgr255** [comment]
So there's no one-size-fits-all solution. We have to tell our Windows users to use `py -3 -m pip` and everyone else to use `python3 -m pip`. But that's not a big deal; unlike processor architecture, most users normally know what general OS they're on.

**Comment by Vgr255** [comment]
Discussed briefly with woffle on IRC, we could probably include a "dummy" `typing` module in the case our users don't want static type checking and don't install Mypy. I'm not sure how much we can allow ourselves to diverge (that's what this issue is about!), but here's the quick code I'd use in a hypothetical `dummy_typing` module:

```
class _faketypehint:
    def __getitem__(self, key):
        return self

_faketypehint = _faketypehint()
```

And then we assign the `_faketypehint` to all the names we otherwise use. Thoughts? (I personally really don't like this approach and would rather force users to have `typing` installed than try to add a clever hack)

**Comment by jacob1** [comment]
If the hack is only a few lines like that it isn't much of a problem. But having dependencies isn't bad either. When attempting to start the bot and if you don't have the right dependencies, it should just display a message telling you to run the install command.

**Comment by skizzerz** [comment]
Cleaning up old discussions. Since nothing happened here for over a year, I'm assuming things are good enough as-is. Re-open this issue if necessary.

Moving forward, we'll try to add typehints where feasible, with a long term goal of hinting everything. Adding the typing module to requirements.txt seems to be the right way forward.
