### ISSUE TITLE
Random target selection

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#241]
Have some way to designate that the target of a command should be selected randomly, either via a new command prefix like !rsee, !rkill, etc. or by a special target nick (that could never be a real nick), like !see ? or something like that.

Channel is a bit divided as to whether or not this is a good thing, below is a summary of some of the pros and cons that were raised.

Pros:
- People can select randomly anyway, this just makes it a bit easier

Cons:
- Selecting randomly is usually never the optimal strategy for any given situation

**Comment by Vgr255** [comment]
Players (especially ##werewolf players) will always go the easiest route, and, even though most don't use logical thinking in the games, having such a feature would just ease bad strategy (if that can even be called strategy), and reduce the already-low level of logic needed to play. Consider me a solid -1.

**Comment by Avamander** [comment]
Take a regular game 4p night. It varies from 2sec to 6, rarely more. During that night, one has to see quickly and then hint. Making people rely on their typing speed and network. 

So kill nick1 becomes rkill, so what? Still a random person dies. But you have a point, doing that after n1 is just a bad decision, but again, people don't need a bot command to make dumb stuff, they just do.

**Comment by skizzerz** [comment]
Closing for now, no huge support and it's not something players can't already do anyway by themselves. Reopen if needed.
