### ISSUE TITLE
Errors: Explode, or try to walk with nails in the feet?

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#252]
Python's philosophy says we should explode when an error occurs. If we try to recover from a half-working state, I'd rather it just stop all callers from executing rather than just pretending like nothing happened (and also returning `None`).

Thoughts? If I see no clear objections I'm going to do this.

**Comment by kernelpanic3** [comment]
Generally, I would vote for exploding immediately and fatally, rather than trying to recover from a half-working state at all. It's risky to _assume_ the next caller isn't going to vomit all over the database or cause similar havoc trying to do something.

**Comment by Vgr255** [comment]
Done in d602a33

**Comment by nyuszika7h** [comment]
How does that make it explode? It just adds more error logging.

**Comment by Vgr255** [comment]
No, it actually forces it to make the error propagate all the way to the top caller. This means that errors happening in some game code will no longer allow that code to keep running and pretend nothing happened, as it used to do (it was an error in the design).

**Comment by nyuszika7h** [comment]
Oh ok, I see.
