### ISSUE TITLE
Consistency with debug mode commands and +d

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#253]
`!fday` and `!fnight` currently require the `+d` flag but aren't debug-mode-only. All `+d` commands should be debug-mode-only by default (can be overridden in the config as usual), and we should eliminate the `if` check for debug mode commands, apart from `!exec` and `!eval`, which should not even be able to be enabled in normal mode with `ALLOWED_NORMAL_MODE_COMMANDS`, only by modifying the source, per @skizzerz's comment on IRC. This would also mean `!revealroles` won't be debug-only as we don't want to give people requesting that `+d`, obviously, but that should be fine, as it's heavily restricted (even for admins) outside debug mode.

**Comment by jacob1** [comment]
what flag would !fday and !fnight require after this change? Right now we have one person with +d in order for them to have both of those commands, but they probably want the +d removed anyway ...

I agree commands like that which aren't really debug mode only (for us) shouldn't be. !fnight is useful for ops in stalemates.

And yeah !exec and !eval should never ever be enabled outside of debug mode. We've had sanity checks against that forever, so should keep them.

**Comment by nyuszika7h** [comment]
Well, I don't know, we could also remove +d requirement from !fday and !fnight. But then !fgame is also useful in normal mode, so I don't know. Just make +d mean all commands which are debug-only by default (well, except !exec and !eval) to avoid multiple definitions of "debug" or so.

**Comment by Fudster** [comment]
I am willing to help implement this once you decide on the required modes.

**Comment by skizzerz** [comment]
This has been fixed when I re-did the flags and commands. Things that are +d are debug-mode only by default, and things like fnight/fday were split into their own flags. exec/eval can never be enabled in normal mode.
