### ISSUE TITLE
Should we require pull requests?

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#257]
Right now, a core group of people can push directly to master, where everyone else needs to open a PR. However, said core group of people often gets things wrong, and then needs to make 3-4 follow-up commits to fix things that maybe would have been caught by someone else just briefly looking over the change. It also allows some questionable design choices or algorithms to slip through that could be better done some other way (example for myself: hand-rolling something that python natively supports via some other method, such as the proxy classes vs function-level imports to break import loops).

I feel that requiring a PR in all cases, even from the core group, would be better for the project. It will slightly slow down development, but that slowdown is to ensure a solid and well-designed commit, which is more than a fair trade for me.

**Comment by jacob1** [comment]
I have a few issues with the way it is set up now. From what I can tell, there is absolutely no way for us to push or merge anything without having another dev merge our pull request? If i'm the only one online and there is some bug I want to fix (possibly major), the only way to fix it would be to disable some of the protection, or wait for another dev to come on.

I think more pull requests would be a good thing, they can sometimes help find bugs (I was going to pull request the mayor split no matter what anyway). I just don't think forcing them in 100% of cases is a good thing for a project as small and rapidly changing as ours. Pull requests for important bug fixes shouldn't be required.

I feel like this model works best for larger, more stable projects, which may even have separate stable and development branches. But lykos always uses the latest commit.

**Comment by skizzerz** [comment]
Sadly, GitHub doesn't offer anything in-between. If we're going to apply restrictions, they should apply evenly across every developer, with no special access afforded to repo owners. The only way to do this with the settings available is to require that every PR is reviewed.

The fact lykos runs on the latest commit is exactly why I want these restrictions. Too often has the latest commit been horribly broken, and the fix been obvious to someone else looking at it. I think every core developer is guilty of this at least once (I know I am). By forcing a PR, that requires that someone glances at it and can spot any obvious issues.

Rushed fixes are also a problem, and I know that I've been guilty of those as well (as have many others). If lykos is super broken due to a major bug, the correct response would be to roll back the bot via git reset --hard and then address the issue properly rather than rushing half-baked code out the door. Said half-baked code often doesn't fix the bug, or if it does it's a horrible hack that goes against design sensibilities and would require a rewrite anyway. Better to just take a bit of extra time and get it as good as feasible the first time around.

**Comment by jacob1** [comment]
I think going from no restrictions to full restrictions is a bit too much, but I guess if you insist we can see how well this works out.

And yes we are all guilty of pushing broken or rushed commits sometimes.

Rushed fixes can be a problem, and they happen, although rare. More often is valid fixes to rushed commits that weren't properly tested. Hopefully that will happen less now. I still think we will need a lot of bugfix commits though, because the massive refactors we have been doing will cause problems that nobody will see in a PR. Changing game and user-handling logic causes obscure bugs that may not be obvious (like mayor+desperation totem). I guess in cases like that we can just ssh into the server and reset back to an older version until another dev comes to merge our fix, hopefully the broken commit wouldn't be too far back ...

**Comment by Vgr255** [comment]
If we're going with the restricted push approach, we should still be able to self-merge PRs. I also think it's really stupid to require PRs to begin with - encourage them, sure, but some small bugfix shouldn't have to go through a PR, that's just dumb.

**Comment by Vgr255** [comment]
I'm not on IRC right now, but I noticed that the default branch is master yet again. Is there something I missed?

**Comment by nyuszika7h** [comment]
That was me who changed it, though we should probably discuss it. I think master should be the default because that's where pull requests go by default and it's easy to tell people to do `git checkout stable`, plus the current stable branch is actually buggier than master.

And I'm really thinking we should not have a stable branch and use tagged releases – it's hard to merge bugfixes into stable without either

* cherry-picking which results in duplicate commits, and everything merged to stable after those will also be a duplicate commit
* force-pushing away the cherry-picked bugfixes whenever we decide to update the stable branch to a newer point in master
* merging the master branch when there are bugfixes and potentially breaking things as it may include feature changes which may or may not be buggy

**Comment by Vgr255** [comment]
Fwiw I'm +1 on the idea.

**Comment by nyuszika7h** [comment]
You know, you can just use the reaction buttons for that if you don't have anything else to add right now :P

**Comment by jacob1** [comment]
We're going to have to force push (or make a ton of branches) no matter what we do. Right now master is buggy, but stable also has a few bug fixes we want to cherry-pick onto it.

If I understand git correctly, we can force push a tag, and then "git checkout <tag>". As long as the user has no uncommitted modifications to existing files, this should work. Maybe !fpull could somehow checkout the latest tag.

So also +1 on using tags somehow, we just need to do it properly.

**Comment by nyuszika7h** [comment]
Er, no, why would you force push to a tag? That's even worse than a stable branch, you're doing the same thing but abusing tags for it. You're not supposed to change an already released version. Just push to like 0.1.1 and tell people to checkout that tag. Though we'll need to fix !pull / !update to handle that, like I said.

**Comment by jacob1** [comment]
Update from what we discussed on IRC:

You can cherry-pick commits onto a new tag, there doesn't have to be a matching branch. We don't ever need to force push/use many branches to do this, we can probably do it all on master. So, ignore my previous suggestion (I thought it was the only way)

Also, we can probably modify !fpull somehow to get the list of tags and checkout the latest one (with an option to just get the latest commit instead, like we currently do)

**Comment by nyuszika7h** [comment]
Yep, it would just pull if you're on master, otherwise checkout the latest tag. Maybe we could have an option to switch to not have to do it manually.

**Comment by skizzerz** [comment]
Using detached tags (tags pointing at orphaned commits) is something I strongly oppose. We should just do what pretty much every other project does, and have stable/release branches we cherry-pick bugfixes to. When it gets too annoying to cherry-pick things, we can cut a new stable/release branch from a later point on master (to basically fast-forward it and include everything up to that point).

Duplicated commits due to cherry-pick (aka multiple hashes for the same commit) is a non-issue -- any individual branch does *not* have duplicate commits, so it doesn't make the history messy at all. We never merge stable/release branches into master or master into stable/release branches, we only cherry-pick from master to the stable/release branch.

Having branches instead of tags means that all the commit git utilities (such as pull) work properly. With orphaned tags, you not only need to know what tag you're pulling to, but you also don't support people having local modifications (local gamemodes.py, etc.) that are checked into git. Since the default fpull/update would be to check out that tag, it would unversion their local stuff and make them lose whatever history they had on it until they drop to cli and merge the tag into their local branch.

**Comment by skizzerz** [comment]
Closing, we've decided to not require PRs in all cases, just when they'd make sense.
