### ISSUE TITLE
!fwarn list should be case-insensitive

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#261]
Doing `!fwarn list JZTech110` works, but `!fwarn list jztech110` doesn't work.

**Comment by Fudster** [comment]
Going to work on this soon.

**Comment by Fudster** [comment]
It seems like this issue has been fixed. in https://github.com/lykoss/lykos/commit/f4876d254e0023856221d1d14b9e2f31b9f77f61

**Comment by jacob1** [comment]
If the player is in the channel it works, otherwise it's still broken

**Comment by Vgr255** [comment]
This works properly now, even for players who aren't in channel or even offline.
