### ISSUE TITLE
Bot pings fake nicks after !fstop

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#265]
```
12:43:46 <rt> !fstop
12:43:47 <@everyone> rt has forced the game to stop.
12:43:47 <@everyone> PING! 1 2 3 4
```

**Comment by Vgr255** [comment]
Side-effect of the user refactoring. Will fix as part of it.

**Comment by Fudster** [comment]
This seems to be fixed. Should be closed.

**Comment by skizzerz** [comment]
Still an issue:
```
<Skizzerz> !fstop
<rolebot> Skizzerz has forced the game to stop.
<rolebot> PING! 
```

If only fakennicks are joined, it says PING! with an empty list instead of omitting the line entirely.

**Comment by nyuszika7h** [comment]
Fixed in master, closing as this is just a minor cosmetic issue and people using the stable branch likely won't be testing with fake nicks anyway.
