### ISSUE TITLE
Revamp !goat

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#276]
As I mentioned earlier on IRC, I believe the way `!goat` works needs to be revisited. Currently, it is pretty much completely useless except for the goat herder (which is the last person who votes to start), which results in `!fgoat` being handed out like candy. Even though we can remove the privileges of abusers, I would find it better to remove `!fgoat` entirely, and make `!goat` work in any phase (even outside games) but put a rate limit it, such as one goat every 5 minutes – either a global or a per-user rate limit, not sure which would be better yet. And possibly get rid of goat herder too.

And if people abuse it, we can simply deny it to them with a warning, like this:

```
!fwarn Example 1 deny=goat Abusing !goat
```

(This is just an example, the number of warning points depends on the situation. We may give out a 0-point warning instead if the user has many warning points and we determine stasis is not deserved.)

**Comment by jnmtx** [comment]
OK, but goat herder would not be subject to 5 minute cooldown. Also, the 5-minute cooldown would be reset: at start of each game day (when a night ends), when a game ends, and when the first vote is issued to start a game. Then you can goat each day still, goat after the game, and goat someone who did !w or voted some weird mode if you want to.

**Comment by Vgr255** [comment]
I think you're missing nyuszika7h's point; `!goat` depending on game state/phase is pretty stupid, and it'd be nice if we could move away from that. Of all the games I've played recently, really few people were ever using it, instead relying on `!fgoat`. The original idea of `!fgoat` was to bypass the restriction, but that doesn't actually do anything useful.

Code-wise, we have weird hacks in the start function only ever used for the goat herder, and I'd like to get rid of that.

**Comment by Vgr255** [comment]
If there's no further objection to this, I'm going to do it once #277 is merged.

**Comment by skizzerz** [comment]
My opinion on the matter:

<woffle> goat: can only goat people on the channel, per-user cooldown (not limited by phase, can be used out of game), eliminate goat herder
<woffle> fgoat: can goat arbitrary strings, no cooldown

There is still a place for fgoat, so I'm against removing it entirely. For cooldown, imo 5 minutes seems good (with an auto-reset on start of day should that end up being shorter)

**Comment by skizzerz** [comment]
Fixed in #286
