### ISSUE TITLE
TODO: Remove hard Coded messages

### ISSUE THREAD

**Issue by Fudster** [lykoss/lykos#282]
Such as https://github.com/lykoss/lykos/blob/stable/src/wolfgame.py#L6937

EDIT: #209

**Comment by nyuszika7h** [comment]
Duplicate of #209.

(This is just for tracking purposes, there is nothing that needs to be done with this issue. See [here](https://github.com/blog/2398-manage-issues-and-pull-requests-with-keyword-updates).)
