### ISSUE TITLE
!pingif does not retrieve latest preference not yet saved to the DB before restart

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#293]
Let's say you have your pingif preference set to 7. (This is an arbitrary example to make it easier to explain – it should work with any number.) Then you do `!pingif 1`. The bot will now ping you when 1 player is joined. However, doing `!pingif` tells you it will ping you at 7p, and doing `!pingif 7` tells you it's already set to 7 and doesn't change the preference back from 1. After the bot is restarted, the preference of 1 will be retrieved from the DB and the same issue happens except it's stuck at 1 instead.

**Comment by Vgr255** [comment]
Fixed in 3f9f066.
