### ISSUE TITLE
Revealroles should show who/what was seen at night, and who’s lycan/ill during the day.

### ISSUE THREAD

**Issue by Michagogo** [lykoss/lykos#310]
I’m on vacation next week, so I _might_ take a look myself.

**Comment by skizzerz** [comment]
Statuses (lycanthropy, misdirected, protected, etc.) are now shown in revealroles. Things like who seer saw are not actually tracked in the bot, and I don't feel that tracking them just for revealroles is particularly useful to have. As such, closing this.
