### ISSUE TITLE
Protection doesn't block gunner night kills and it should

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#323]
Also don't think it blocks gunner day kills either -- should do that too maybe, idk.

**Comment by ammongit** [comment]
If it affects day kills, then other totems like revealing should affect them as well. I think totem effects should be limited to gunner night kills.

**Comment by skizzerz** [comment]
revealing only applies on lynch, that's an entirely different beast.

There is a lot of precedent for protections blocking day kills which aren't lynches:
- assassin assassinate
- dullahan spine whip
- mad scientist splash

The only role that can kill during the daytime that isn't on that list is gunner. Protections working during day isn't a new thing, and gunner is oddly inconsistent with literally every other role in that regard.

**Comment by ammongit** [comment]
Hmm I see. In that case, I agree that gunner shots shouldn't be treated differently from other deaths.
Will protection guard against _any_ attempt to shoot, or just those that hit, or just those that would've killed?

**Comment by skizzerz** [comment]
Protection now works against gunner night kills (although not day kills yet, but that isn't the title of the bug)
