### ISSUE TITLE
Overhaul village drunk

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#332]
Suggested changes:
- Rename `village drunk` to `drunk`
- Turn drunk into a secondary role that can be applied on (almost?) everyone
- By default, a drunk person is considered as having a permanent misdirection totem on them, but they never get told which target ends up being picked
- Drunk gunner is not misdirected and still gets 3x shots
- Drunk killer (wolf role, hunter, vigilante, etc.) has a chance of waking up whoever they're targeting (behaviour undefined)
- Doomsayer doesn't know *what* happens upon `!see`
- Fallen angel has a chance of not piercing protection or piercing two prots (or also only piercing one)
- Alpha bite might kill instead
- Prophet might not get back useful info, or might get useful info right away
- Drunk doctor gets many immunizations
- Drunk mad scientist explodes two people over (instead of just one) on each side
- Drunk matchmaker doesn't pick lovers
- Drunk jester behaves like fool
- Drunk fool behaves like jester
- Drunk amnesiac takes one more (or less?) night to remember
- Drunk clone doesn't know they've cloned
- Drunk wild child doesn't know who is their idol
- Succubus can become drunk upon visiting a drunk, and everyone a drunk succubus visits becomes drunk

These are quick ideas, might not be balanced. Open for discussions.

**Comment by jacob1** [comment]
A lot of these suggestions I don't really like.

A permanent misdirection totem sounds extremely annoying, especially for some roles.
Then you say it wouldn't apply to gunner, which is a strange (but required if we were doing that) exception.

Not sure what you mean by "waking them up", would they be notified who you are? (yes, I know you said behavior was currently undefined). Random chances are also often annoying. A lot of the other stuff in this list is random chance. It technically goes along with how drunk gunner is currently (worse random odds), but it's still annoying if it breaks your core role.

Drunk mad scientist thing would confuse anyone trying to calculate who is safe to kill. I'd rather not change that.

Swapping fool and jester is also stupid, if we're applying drunk like template, we probably shouldn't allow these or most neutrals to get it if it won't have any affect.

Most of the rest of the list is just having the bot automatically pick things for you, and possibly not telling you. Seems strange to me, if anything just have it randomly pick and still tell you. I wouldn't want to be wild child who doesn't know who my idol is.

Drunk succubus thing sounds somewhat interesting, if we were doing that it should probably also apply to harlot? Makes things more complicated, anyway.

**Comment by skizzerz** [comment]
Closing this as most of this is not going to happen anyway.
