### ISSUE TITLE
Never send the simple message if the player has never played a certain role

### ISSUE THREAD

**Issue by Vgr255** [lykoss/lykos#333]
Proposition:

- Rename `User.prefers_simple` to `User.get_role_string` (bikeshed name)
Pseudo-code:
```
class User(IRCContext):
    ...
    def get_role_string(self, role):
        rolename = role.replace(" ", "_")
        msg = rolename + "_notify"
        < check database for whether or not 'self' has played 'role' >
        if has_played:
            < check database for whether or not 'self' prefers simple >
            if prefers_simple:
                msg = rolename + "_simple"
        return msg
```
- Have all of roles simply do `key = user.get_role_string(role)` and then use that
- Ensure that all roles follow the same message key naming convention (`rolename + "_" + {"simple", "notifiy"}`)

This makes sure that experienced players get proper information for roles that get added even when they have !simple enabled. Currently, people who have !simple on get penalized when they play a role that has only just been implemented, as they don't get proper information about it (and often there is no wiki entry for a role that's just been added in). This won't matter most of the time, but it makes code simpler overall while helping in some cases.

**Comment by skizzerz** [comment]
Simple is now removed, closing
