### ISSUE TITLE
Warn if certain roles cause a timeout during night

### ISSUE THREAD

**Issue by shentino** [lykoss/lykos#375]
If a player with one of some roles causes a timeout during a standard 2 minute night, issue a warning.

Examples:

Seer going afk during night and failing to vote within the 2 minute deadline

Rationale:

If you have certain roles, idling out at night and causing lykos to time out has at least as much impact as idle-dying during the day and it's a good way to screw your own team over if you waste an opportunity to use your role.

Exceptions:

Time lord.

Endorsements:

moonmoon

**Comment by jacob1** [comment]
Added in #422
