### ISSUE TITLE
CS doesn't have enough totems

### ISSUE THREAD

**Issue by MishaCatskill** [lykoss/lykos#384]
give CS more totems

(at least 2, and 3 at higher player counts?)

**Comment by T0ML** [comment]
Yes please, YES YES and MORE YES

**Comment by MishaCatskill** [comment]
This has been discussed some on IRC, and it's true that too many totems every night would be chaotic. It should determine the number by living player count at the start of night. I think 2 totems at 9p would be a good starting point. That way CS will basically always get to double totem once per game (a big plus imo), but in games smaller than about 12 it will _only_ happen n1. Add a third at 17p like gunner bullets, maybe?

**Comment by skizzerz** [comment]
Not going to happen in general, and not in default. I can see it happening for some future mode that is designed to accommodate extra CS totem shenanigans though.

**Comment by jacob1** [comment]
test plz ignore
