### ISSUE TITLE
Two harlots visiting each other are invincible from wolf kills

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#387]
harlot1 is targeted, but doesn't get killed since they aren't home.
harlot2 was there, but the check that kills the visiting harlot doesn't trigger unless the person being visited dies.

end result is that wolves can't kill either

**Comment by skizzerz** [comment]
I think the way I want to fix this is to prevent a harlot from visiting someone if they are currently being visited.

Does anyone see any issues with that?

**Comment by jacob1** [comment]
It would make more sense "lore"-wise. I don't mind that change.
