### ISSUE TITLE
Duplicate message when guarding self and getting killed by fallen angel

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#390]
&lt;lykos> A fell wind starts blowing through the village and you catch the flurry of blackened wings out of the corner of your eye. No longer caring for jacob1's safety, you attempt to get away before your own life is taken...
&lt;lykos> A fell wind blows through you and chills you to the bone. You no longer feel safe or protected...

**Comment by rdococ** [comment]
What should be the replacement message? Something like this?

<lykos> A fell wind starts blowing through the village and you catch the flurry of blackened wings out of the corner of your eye. You attempt to get away before your life is taken...

**Comment by skizzerz** [comment]
Just don't have the first message at all. The second one "You no longer feel safe or protected" should suffice.
