### ISSUE TITLE
"No Victims" message sometimes not playing

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#396]
in a sleepy game, dullahan targeted priest and wolves seer. No message was displayed:

&lt;lykos> Night lasted 01:18. It is now daytime. The villagers awake, thankful for surviving the night, and search the village... 
&lt;lykos> The villagers must now vote for whom to lynch. Use "!lynch &lt;nick>" to cast your vote. 5 votes are required to lynch.

This also happened later on in a mudkip game, when wolves targeted the blessed investigator.

**Comment by skizzerz** [comment]
Fixed in 8d4f0f08a57b042b1e2a45c9627e24727d45a09b
