### ISSUE TITLE
Mudkip suicide pacts don't end the game

### ISSUE THREAD

**Issue by fndax** [lykoss/lykos#397]
From mudkip's wikipage:

> The person with the plurality of votes is lynched, and should there be a tie, all tied players are lynched simultaneously. 

We decided to form a suicide pact and everyone got 1 vote. Instead of all tied players being lynched simultaneously, nobody got lynched. This made me very very sad.

If this is unintended behavior, plz fix. If this is intended behavior, plz close as invalid and update wiki.

**Comment by jacob1** [comment]
The wiki is correct. What should have happened is that all players get lynched, and nobody wins.

Can you provide logs of the game?

**Comment by bugmen0t** [comment]
https://0bin.net/paste/OFexPGmkV-mW-YOC#O3TAl0XxZNj0-jzY7L1puBZizEjx82v886NBjW/V6zg

**Comment by jacob1** [comment]
I checked the code and I was wrong, there is an exception for this.
https://github.com/lykoss/lykos/blob/master/src/votes.py#L243

The comment is very accurate ... the move to kill everyone was wrong, you shouldn't intentionally try to lose. It would have made more sense to try to figure out which GA was fake.

**Comment by skizzerz** [comment]
Not a bug. It's anticipated that wolfteam wouldn't go along with the suicide pact and change their vote at the last minute to kill someone else off, which is why this is a terrible idea.
