### ISSUE TITLE
Extra vengeful ghosts in boreal if multiple shamans starve in one night

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#404]
4 people turned to VG in one night. Happened the last night of the game.

Full logs, scroll down to bottom:
Sun 11-24 [18:23:59] &lt;lykos&gt; el, rdococ, sust, jacob1, Ramona, zoid, nyuszika7h, dax, Faely, misha, aismallard, and hexa-: Welcome to Werewolf, the popular detective/social party game (a theme of Mafia). Using the boreal game mode with unrestricted abstaining.
Sun 11-24 [18:23:59] * lykos sets mode +m ##werewolf
Sun 11-24 [18:24:00] &lt;lykos&gt; It is now nighttime. All players check for PMs from me for instructions.
Sun 11-24 [18:24:00] &lt;lykos&gt; The tribe is hungry and needs to be fed 3 times tonight. They have gone hungry 0 times in the past.
Sun 11-24 [18:24:04] &lt;aismallard&gt; ...
Sun 11-24 [18:24:05] &lt;misha&gt; feeding the tribe
Sun 11-24 [18:24:06] &lt;dax&gt; feeding tribe
Sun 11-24 [18:24:08] &lt;el&gt; because most games today have been boreal
Sun 11-24 [18:24:09] &lt;aismallard&gt; feed tribe
Sun 11-24 [18:24:10] &lt;jacob1&gt; who wants revealing
Sun 11-24 [18:24:11] &lt;el&gt; feeding tribe
Sun 11-24 [18:24:13] &lt;misha&gt; pls2not feed the tribe hunger totems
Sun 11-24 [18:24:15] &lt;aismallard&gt; jacob1: me!
Sun 11-24 [18:24:18] &lt;jacob1&gt; revealing to aismallard !
Sun 11-24 [18:24:21] &lt;rdococ&gt; giving revealing to misha
Sun 11-24 [18:24:22] &lt;sust&gt; fed tribe
Sun 11-24 [18:24:28] &lt;dax&gt; el: yes, for testing. i've been trying to make sure we have a game or three of non-boreal in between
Sun 11-24 [18:24:29] &lt;hexa-&gt; feeding sust
Sun 11-24 [18:24:32] &lt;rdococ&gt; actually, I'll give it to sust
Sun 11-24 [18:24:48] &lt;sust&gt; mmmm foooood
Sun 11-24 [18:24:49] &lt;dax&gt; el: i think we're up to 9 total (including this game) boreal since balance changes, gonna stop pushing for testing once we hit 10 personally
Sun 11-24 [18:24:58] &lt;Faely&gt; I has sust
Sun 11-24 [18:25:03] &lt;zoid&gt; oh fuck me.
Sun 11-24 [18:25:04] &lt;Ramona&gt; still confused lol
Sun 11-24 [18:25:11] &lt;sust&gt; Faely: feed the tribe
Sun 11-24 [18:25:12] &lt;zoid&gt; wolf shaman please kill me.
Sun 11-24 [18:25:13] &lt;Faely&gt; anyone else feeding trube?
Sun 11-24 [18:25:14] &lt;Faely&gt; k
Sun 11-24 [18:25:14] &lt;rdococ&gt; I would like cs totem
Sun 11-24 [18:25:15] &lt;misha&gt; Ramona: what totem do you have?
Sun 11-24 [18:25:29] &lt;lykos&gt; A few villagers awake early and notice it is still dark outside. The night is almost over and there are still whispers heard in the village.
Sun 11-24 [18:25:32] &lt;el&gt; if anyone has dt zoid would like it
Sun 11-24 [18:25:35] &lt;zoid&gt; ^
Sun 11-24 [18:25:45] &lt;misha&gt; inb4 Ramona has hunger totems
Sun 11-24 [18:25:50] &lt;jacob1&gt; maybe lol
Sun 11-24 [18:25:51] &lt;Faely&gt; who else is feeding tribe?
Sun 11-24 [18:25:54] &lt;misha&gt; i am
Sun 11-24 [18:25:55] &lt;zoid&gt; feeding tribe
Sun 11-24 [18:25:56] &lt;el&gt; me
Sun 11-24 [18:25:57] &lt;aismallard&gt; ...
Sun 11-24 [18:25:59] &lt;lykos&gt; Night lasted 02:00. It is now daytime. The villagers awake, thankful for surviving the night, and search the village... 
Sun 11-24 [18:25:59] &lt;lykos&gt; The night is over, but the storm still rages outside. The tribe elder estimates the storm will subside in 6 more days.
Sun 11-24 [18:25:59] &lt;lykos&gt; Ramona seems to be in possession of a mysterious totem...
Sun 11-24 [18:25:59] &lt;lykos&gt; aismallard seems to be in possession of a mysterious totem...
Sun 11-24 [18:25:59] &lt;lykos&gt; el seems to be in possession of a mysterious totem...
Sun 11-24 [18:25:59] &lt;lykos&gt; lykos seemed to be in possession of 8 mysterious totems...
Sun 11-24 [18:25:59] &lt;lykos&gt; misha seems to be in possession of a mysterious totem...
Sun 11-24 [18:25:59] &lt;lykos&gt; sust seems to be in possession of 2 mysterious totems...
Sun 11-24 [18:25:59] &lt;lykos&gt; The villagers must now vote for whom to lynch. Use "!lynch &lt;nick&gt;" to cast your vote. 7 votes are required to lynch.
Sun 11-24 [18:26:00] &lt;jacob1&gt; Faely: ctrl+f "fee"
Sun 11-24 [18:26:02] &lt;rdococ&gt; Ramona is obvwoof
Sun 11-24 [18:26:03] &lt;aismallard&gt; !v ais revealing
Sun 11-24 [18:26:03] &lt;lykos&gt; aismallard votes for aismallard.
Sun 11-24 [18:26:06] &lt;dax&gt; yay tribe got fed
Sun 11-24 [18:26:08] &lt;Faely&gt; excuse me EIGHT?
Sun 11-24 [18:26:11] &lt;rdococ&gt; wow 8 totens
Sun 11-24 [18:26:11] &lt;sust&gt; 8
Sun 11-24 [18:26:11] &lt;jacob1&gt; :O
Sun 11-24 [18:26:12] &lt;rdococ&gt; totems
Sun 11-24 [18:26:13] &lt;Faely&gt; people??
Sun 11-24 [18:26:16] &lt;nyuszika7h&gt; !v ais
Sun 11-24 [18:26:16] &lt;lykos&gt; nyuszika7h votes for aismallard.
Sun 11-24 [18:26:16] &lt;jacob1&gt; that's the most I've ever seen lol
Sun 11-24 [18:26:17] &lt;aismallard&gt; lol 8 lykos totems
Sun 11-24 [18:26:18] &lt;Ramona&gt; i was reading the wiki gimmie a break
Sun 11-24 [18:26:20] &lt;misha&gt; rdococ: not necessarily, in any other mode it's not a strategy for shaman to say who  they're toteming and what totem n1
Sun 11-24 [18:26:20] &lt;Faely&gt; !v ais
Sun 11-24 [18:26:20] &lt;lykos&gt; Faely votes for aismallard.
Sun 11-24 [18:26:23] &lt;el&gt; !v ais
Sun 11-24 [18:26:23] &lt;lykos&gt; el votes for aismallard.
Sun 11-24 [18:26:23] &lt;jacob1&gt; !vote aismallard 
Sun 11-24 [18:26:23] &lt;misha&gt; !v aismallard 
Sun 11-24 [18:26:24] &lt;lykos&gt; misha votes for aismallard.
Sun 11-24 [18:26:24] &lt;lykos&gt; jacob1 votes for aismallard.
Sun 11-24 [18:26:24] &lt;dax&gt; !lynch aismallard 
Sun 11-24 [18:26:24] &lt;lykos&gt; dax votes for aismallard.
Sun 11-24 [18:26:24] &lt;lykos&gt; Before the rope is pulled, aismallard's totem emits a brilliant flash of light. When the villagers are able to see again, they discover that aismallard has escaped! The left-behind totem seems to have taken on the shape of a shaman.
Sun 11-24 [18:26:24] &lt;rdococ&gt; !v sust also got rev
Sun 11-24 [18:26:24] &lt;hexa-&gt; !v ais
Sun 11-24 [18:26:25] &lt;lykos&gt; Day lasted 00:25. It is now nighttime. All players check for PMs from me for instructions. If you did not receive one, simply sit back, relax, and wait patiently for morning.
Sun 11-24 [18:26:26] &lt;lykos&gt; The tribe is hungry and needs to be fed 3 times tonight. They have gone hungry 0 times in the past.
Sun 11-24 [18:26:26] &lt;jacob1&gt; yay
Sun 11-24 [18:26:26] &lt;aismallard&gt; nice
Sun 11-24 [18:26:29] &lt;el&gt; nice
Sun 11-24 [18:26:29] &lt;dax&gt; feeding tribe
Sun 11-24 [18:26:30] &lt;nyuszika7h&gt; !stats
Sun 11-24 [18:26:30] &lt;lykos&gt; nyuszika7h: 12 players: el, rdococ, sust, jacob1, Ramona, zoid, nyuszika7h, dax, Faely, misha, aismallard, hexa-
Sun 11-24 [18:26:30] &lt;lykos&gt; nyuszika7h: It is currently night. There are 3 wolf shamans, and 9 shamans.
Sun 11-24 [18:26:32] &lt;aismallard&gt; I have revealing, giving to misha
Sun 11-24 [18:26:32] &lt;el&gt; sust, feeding agan
Sun 11-24 [18:26:35] &lt;hexa-&gt; feeding tribe
Sun 11-24 [18:26:36] &lt;jacob1&gt; pacifism ):
Sun 11-24 [18:26:38] &lt;sust&gt; i got silence
Sun 11-24 [18:26:38] &lt;jacob1&gt; giving to Ramona
Sun 11-24 [18:26:42] &lt;aismallard&gt; vote misha tomorrow!
Sun 11-24 [18:26:44] &lt;el&gt; paci ramona
Sun 11-24 [18:26:47] &lt;rdococ&gt; I have sust
Sun 11-24 [18:26:47] &lt;misha&gt; i have sust, who shall i give it to?
Sun 11-24 [18:26:49] &lt;aismallard&gt; they'll be the best kitten-mayor this village has ever had!
Sun 11-24 [18:26:49] &lt;sust&gt; who 2 silence
Sun 11-24 [18:26:53] &lt;rdococ&gt; feeding tribe
Sun 11-24 [18:26:57] &lt;dax&gt; give sust to tribe unless someone says they're hungry
Sun 11-24 [18:26:57] &lt;misha&gt; sust: Ramona maybe
Sun 11-24 [18:27:03] &lt;el&gt; over feed tribe
Sun 11-24 [18:27:06] &lt;Faely&gt; who wants sust
Sun 11-24 [18:27:10] &lt;dax&gt; there's 3 WSes, you want to feed the hell out of tribe
Sun 11-24 [18:27:10] &lt;sust&gt; stop trying to feed me to people
Sun 11-24 [18:27:12] &lt;zoid&gt; feeding tribe
Sun 11-24 [18:27:13] &lt;el&gt; it got very hungered last night
Sun 11-24 [18:27:14] &lt;sust&gt; thanks
Sun 11-24 [18:27:18] &lt;rdococ&gt; eating sust
Sun 11-24 [18:27:19] &lt;Faely&gt; dax: good point
Sun 11-24 [18:27:30] &lt;sust&gt; silencing Ramona 
Sun 11-24 [18:27:38] &lt;Faely&gt; el: it didn't get hungry last night though
Sun 11-24 [18:27:39] &lt;Ramona&gt; rude
Sun 11-24 [18:27:49] &lt;rdococ&gt; hmm
Sun 11-24 [18:27:50] &lt;rdococ&gt; idea:
Sun 11-24 [18:27:54] &lt;lykos&gt; A few villagers awake early and notice it is still dark outside. The night is almost over and there are still whispers heard in the village.
Sun 11-24 [18:28:03] &lt;rdococ&gt; can we use silencing and totem counts to determine woof?
Sun 11-24 [18:28:04] &lt;sust&gt; jacob1: multitotem shamans when
Sun 11-24 [18:28:08] &lt;rdococ&gt; because wolf shamans usually get 2 totems
Sun 11-24 [18:28:11] &lt;el&gt; Faely: it needs feeding 3 times, and 3 ws can fuck it anyway
Sun 11-24 [18:28:12] &lt;jacob1&gt; sust: that's ... already a thing
Sun 11-24 [18:28:15] &lt;misha&gt; rdococ: i think less than before but yeah
Sun 11-24 [18:28:15] &lt;jacob1&gt; in this mode
Sun 11-24 [18:28:15] &lt;sust&gt; oh
Sun 11-24 [18:28:17] &lt;Faely&gt; right
Sun 11-24 [18:28:18] &lt;aismallard&gt; lol
Sun 11-24 [18:28:24] &lt;lykos&gt; Night lasted 02:00. It is now daytime. The villagers awake, thankful for surviving the night, and search the village... 
Sun 11-24 [18:28:24] &lt;lykos&gt; The night is over, but the storm still rages outside. The tribe elder estimates the storm will subside in 5 more days.
Sun 11-24 [18:28:24] &lt;lykos&gt; The dead body of rdococ, a shaman, is found. Those remaining mourn the tragedy.
Sun 11-24 [18:28:24] * lykos removes voice from rdococ
Sun 11-24 [18:28:24] &lt;lykos&gt; Ramona seems to be in possession of 2 mysterious totems...
Sun 11-24 [18:28:24] &lt;lykos&gt; jacob1 seems to be in possession of a mysterious totem...
Sun 11-24 [18:28:24] &lt;lykos&gt; lykos seemed to be in possession of 6 mysterious totems...
Sun 11-24 [18:28:24] &lt;lykos&gt; misha seems to be in possession of a mysterious totem...
Sun 11-24 [18:28:24] &lt;lykos&gt; nyuszika7h seems to be in possession of a mysterious totem...
Sun 11-24 [18:28:24] &lt;lykos&gt; rdococ seemed to be in possession of a mysterious totem...
Sun 11-24 [18:28:24] &lt;lykos&gt; The villagers must now vote for whom to lynch. Use "!lynch &lt;nick&gt;" to cast your vote. 6 votes are required to lynch.
Sun 11-24 [18:28:28] &lt;aismallard&gt; !v misha revealing
Sun 11-24 [18:28:29] &lt;lykos&gt; aismallard votes for misha.
Sun 11-24 [18:28:31] &lt;nyuszika7h&gt; !v misha
Sun 11-24 [18:28:31] &lt;lykos&gt; nyuszika7h votes for misha.
Sun 11-24 [18:28:31] &lt;zoid&gt; !v misha
Sun 11-24 [18:28:31] &lt;lykos&gt; zoid votes for misha.
Sun 11-24 [18:28:32] &lt;dax&gt; !lynch misha revealing
Sun 11-24 [18:28:32] &lt;lykos&gt; dax votes for misha.
Sun 11-24 [18:28:34] &lt;jacob1&gt; who killed rd lol
Sun 11-24 [18:28:35] &lt;sust&gt; !v mis
Sun 11-24 [18:28:35] &lt;lykos&gt; sust votes for misha.
Sun 11-24 [18:28:35] &lt;lykos&gt; jacob1 impatiently votes for misha.
Sun 11-24 [18:28:35] &lt;lykos&gt; Before the rope is pulled, misha's totem emits a brilliant flash of light. When the villagers are able to see again, they discover that misha has escaped! The left-behind totem seems to have taken on the shape of a shaman.
Sun 11-24 [18:28:36] &lt;el&gt; !v misha
Sun 11-24 [18:28:37] &lt;lykos&gt; Day lasted 00:11. It is now nighttime. All players check for PMs from me for instructions. If you did not receive one, simply sit back, relax, and wait patiently for morning.
Sun 11-24 [18:28:37] &lt;lykos&gt; The tribe is hungry and needs to be fed 2 times tonight. They have gone hungry 0 times in the past.
Sun 11-24 [18:28:37] * random-nick (~random-ni@unaffiliated/random-nick) has quit (Ping timeout: 240 seconds)
Sun 11-24 [18:28:38] &lt;jacob1&gt; ok
Sun 11-24 [18:28:41] &lt;dax&gt; sust again, feeding again
Sun 11-24 [18:28:43] &lt;hexa-&gt; feeding tribe
Sun 11-24 [18:28:43] &lt;misha&gt; so me and aismallard are safe
Sun 11-24 [18:28:45] &lt;zoid&gt; feeding tribe
Sun 11-24 [18:28:46] &lt;jacob1&gt; feeding tribe
Sun 11-24 [18:28:47] &lt;el&gt; revealing
Sun 11-24 [18:28:47] &lt;misha&gt; i have reveal
Sun 11-24 [18:28:48] &lt;Faely&gt; feeding
Sun 11-24 [18:28:48] &lt;sust&gt; feeding tribe
Sun 11-24 [18:28:51] &lt;sust&gt; oh
Sun 11-24 [18:28:51] &lt;zoid&gt; misha, me!
Sun 11-24 [18:28:52] &lt;nyuszika7h&gt; feeding tribe too
Sun 11-24 [18:28:53] &lt;sust&gt; nvm
Sun 11-24 [18:28:53] &lt;el&gt; what are we doing for ramona?
Sun 11-24 [18:28:56] &lt;sust&gt; leme feed someone else
Sun 11-24 [18:29:02] &lt;misha&gt; did Ramona ever say what she's giving to anyone at any point?
Sun 11-24 [18:29:03] &lt;aismallard&gt; who is hungry?
Sun 11-24 [18:29:04] &lt;zoid&gt; misha, can haz revealing?
Sun 11-24 [18:29:07] &lt;nyuszika7h&gt; ramona was silenced btw they may be wolf
Sun 11-24 [18:29:10] &lt;aismallard&gt; misha: give revealing to Ramona imo
Sun 11-24 [18:29:12] &lt;misha&gt; i don't want to give any reveal to Ramona because i'd rather JUST LYNCH HER
Sun 11-24 [18:29:14] &lt;dax&gt; misha: no
Sun 11-24 [18:29:16] &lt;nyuszika7h&gt; since I DTed rdococ
Sun 11-24 [18:29:19] &lt;aismallard&gt; ok
Sun 11-24 [18:29:20] &lt;nyuszika7h&gt; well
Sun 11-24 [18:29:20] &lt;el&gt; revealing ramona too
Sun 11-24 [18:29:21] &lt;misha&gt; because she's getting progressively wolfier every day she won't give any info
Sun 11-24 [18:29:22] &lt;nyuszika7h&gt; there are two others
Sun 11-24 [18:29:26] &lt;nyuszika7h&gt; did they all idle or idek
Sun 11-24 [18:29:38] &lt;lykos&gt; Night lasted 01:02. It is now daytime. The villagers awake, thankful for surviving the night, and search the village... 
Sun 11-24 [18:29:38] &lt;lykos&gt; The night is over, but the storm still rages outside. The tribe elder estimates the storm will subside in 4 more days.
Sun 11-24 [18:29:38] &lt;lykos&gt; Ramona seems to be in possession of a mysterious totem...
Sun 11-24 [18:29:38] &lt;lykos&gt; aismallard seems to be in possession of a mysterious totem...
Sun 11-24 [18:29:38] &lt;lykos&gt; el seems to be in possession of a mysterious totem...
Sun 11-24 [18:29:38] &lt;lykos&gt; lykos seemed to be in possession of 6 mysterious totems...
Sun 11-24 [18:29:38] &lt;lykos&gt; misha seems to be in possession of a mysterious totem...
Sun 11-24 [18:29:38] &lt;lykos&gt; zoid seems to be in possession of a mysterious totem...
Sun 11-24 [18:29:38] &lt;lykos&gt; The villagers must now vote for whom to lynch. Use "!lynch &lt;nick&gt;" to cast your vote. 6 votes are required to lynch.
Sun 11-24 [18:29:41] &lt;sust&gt; fed hex
Sun 11-24 [18:29:41] &lt;jacob1&gt; any deaths going to Ramona ?
Sun 11-24 [18:29:43] &lt;jacob1&gt; ok I guess not
Sun 11-24 [18:29:43] &lt;hexa-&gt; hungry
Sun 11-24 [18:29:43] &lt;aismallard&gt; i'm hungry
Sun 11-24 [18:29:44] &lt;dax&gt; i'm hungry
Sun 11-24 [18:29:44] &lt;misha&gt; i'm hungry
Sun 11-24 [18:29:48] &lt;Faely&gt; ow
Sun 11-24 [18:29:49] &lt;aismallard&gt; !v ramon
Sun 11-24 [18:29:49] &lt;lykos&gt; aismallard votes for Ramona.
Sun 11-24 [18:29:51] &lt;hexa-&gt; sust: thx
Sun 11-24 [18:29:52] &lt;Faely&gt; !v ram
Sun 11-24 [18:29:52] &lt;lykos&gt; Faely votes for Ramona.
Sun 11-24 [18:29:53] &lt;zoid&gt; I'm hungry
Sun 11-24 [18:29:53] &lt;jacob1&gt; meh
Sun 11-24 [18:29:55] &lt;hexa-&gt; !v ramon
Sun 11-24 [18:29:55] &lt;dax&gt; !lynch Ramona 
Sun 11-24 [18:29:55] &lt;lykos&gt; hexa- votes for Ramona.
Sun 11-24 [18:29:55] &lt;lykos&gt; dax votes for Ramona.
Sun 11-24 [18:29:56] &lt;jacob1&gt; !vote Ramona 
Sun 11-24 [18:29:58] &lt;sust&gt; oh
Sun 11-24 [18:29:58] &lt;lykos&gt; jacob1 votes for Ramona.
Sun 11-24 [18:29:58] &lt;el&gt; !v ram
Sun 11-24 [18:29:58] &lt;lykos&gt; el votes for Ramona.
Sun 11-24 [18:29:58] &lt;lykos&gt; Before the rope is pulled, Ramona's totem emits a brilliant flash of light. When the villagers are able to see again, they discover that Ramona has escaped! The left-behind totem seems to have taken on the shape of a wolf shaman.
Sun 11-24 [18:29:59] &lt;sust&gt; i'm dumb
Sun 11-24 [18:30:00] &lt;lykos&gt; Day lasted 00:20. It is now nighttime. All players check for PMs from me for instructions. If you did not receive one, simply sit back, relax, and wait patiently for morning.
Sun 11-24 [18:30:00] &lt;lykos&gt; The tribe is hungry and needs to be fed 2 times tonight. They have gone hungry 0 times in the past.
Sun 11-24 [18:30:00] &lt;aismallard&gt; nice
Sun 11-24 [18:30:01] &lt;zoid&gt; kek
Sun 11-24 [18:30:02] &lt;dax&gt; feeding self
Sun 11-24 [18:30:02] &lt;el&gt; see
Sun 11-24 [18:30:02] &lt;Faely&gt; nice
Sun 11-24 [18:30:02] &lt;sust&gt; nvm i fed the tribe
Sun 11-24 [18:30:03] &lt;aismallard&gt; pacifism
Sun 11-24 [18:30:03] &lt;misha&gt; we should not have revealed Ramona
Sun 11-24 [18:30:03] &lt;jacob1&gt; WHAT
Sun 11-24 [18:30:06] &lt;aismallard&gt; also I need sust
Sun 11-24 [18:30:08] &lt;misha&gt; i am silencing Ramona, someone please feed me
Sun 11-24 [18:30:09] &lt;zoid&gt; feeding tribe
Sun 11-24 [18:30:10] &lt;hexa-&gt; got sust
Sun 11-24 [18:30:14] &lt;jacob1&gt; el did it
Sun 11-24 [18:30:15] &lt;hexa-&gt; feeding aismallard 
Sun 11-24 [18:30:15] &lt;el&gt; i have silence
Sun 11-24 [18:30:16] &lt;dax&gt; feed the people who need feeding
Sun 11-24 [18:30:17] &lt;jacob1&gt; according to logs
Sun 11-24 [18:30:18] &lt;nyuszika7h&gt; someone feed me too
Sun 11-24 [18:30:20] &lt;aismallard&gt; thanks
Sun 11-24 [18:30:21] &lt;sust&gt; gave sust to ais
Sun 11-24 [18:30:21] &lt;nyuszika7h&gt; giving sust to misha
Sun 11-24 [18:30:21] &lt;dax&gt; there are like five of them
Sun 11-24 [18:30:24] &lt;misha&gt; thanks nyuszika7h 
Sun 11-24 [18:30:26] &lt;jacob1&gt; I also need to be fed now :|
Sun 11-24 [18:30:29] &lt;Faely&gt; who needs feeding?
Sun 11-24 [18:30:32] &lt;sust&gt; also
Sun 11-24 [18:30:34] &lt;sust&gt; i need fed
Sun 11-24 [18:30:36] &lt;sust&gt; help
Sun 11-24 [18:30:37] &lt;el&gt; who to silence i can't silence ramona
Sun 11-24 [18:30:40] &lt;Faely&gt; feeding sust
Sun 11-24 [18:30:41] &lt;lykos&gt; Ramona: You have been idling for a while. Please say something soon or you might be declared dead.
Sun 11-24 [18:30:46] &lt;Ramona&gt; ahh 
Sun 11-24 [18:30:55] &lt;el&gt; i can silence myself if you like
Sun 11-24 [18:31:07] &lt;sust&gt; we can just exile Ramona tommorow
Sun 11-24 [18:31:17] &lt;dax&gt; sust said "fed hex" last night but hex didn't get a totem lol
Sun 11-24 [18:31:23] &lt;misha&gt; silence sust then
Sun 11-24 [18:31:28] &lt;sust&gt; dax: i corrected myself
Sun 11-24 [18:31:28] &lt;lykos&gt; A few villagers awake early and notice it is still dark outside. The night is almost over and there are still whispers heard in the village.
Sun 11-24 [18:31:29] &lt;aismallard&gt; ^
Sun 11-24 [18:31:33] &lt;sust&gt; as i typed "feed hex" to lykos
Sun 11-24 [18:31:35] &lt;el&gt; sust silenced
Sun 11-24 [18:31:36] &lt;sust&gt; and actually fed tribe
Sun 11-24 [18:31:37] &lt;hexa-&gt; sust: rude
Sun 11-24 [18:31:40] &lt;sust&gt; by mistake
Sun 11-24 [18:31:41] &lt;dax&gt; sust: ah
Sun 11-24 [18:31:55] &lt;misha&gt; who's idling, is it Ramona?
Sun 11-24 [18:31:57] &lt;misha&gt; !goat Ramona 
Sun 11-24 [18:31:57] &lt;lykos&gt; misha's goat walks by and kicks Ramona.
Sun 11-24 [18:31:58] &lt;lykos&gt; Night lasted 02:00. It is now daytime. The villagers awake, thankful for surviving the night, and search the village... 
Sun 11-24 [18:31:58] &lt;lykos&gt; The tribe was not fed enough last night and looks increasingly on-edge from their hunger.
Sun 11-24 [18:31:58] &lt;lykos&gt; The night is over, but the storm still rages outside. The tribe elder estimates the storm will subside in 3 more days.
Sun 11-24 [18:31:58] &lt;lykos&gt; The dead body of aismallard, a shaman, is found. Those remaining mourn the tragedy.
Sun 11-24 [18:31:58] &lt;lykos&gt; The dead body of el, a vengeful ghost, is found. Those remaining mourn the tragedy.
Sun 11-24 [18:31:58] * lykos removes voice from aismallard el
Sun 11-24 [18:31:58] &lt;lykos&gt; Faely seems to be in possession of a mysterious totem...
Sun 11-24 [18:31:58] &lt;lykos&gt; Ramona seems to be in possession of 2 mysterious totems...
Sun 11-24 [18:31:58] &lt;lykos&gt; aismallard seemed to be in possession of 3 mysterious totems...
Sun 11-24 [18:31:58] &lt;lykos&gt; dax seems to be in possession of 2 mysterious totems...
Sun 11-24 [18:31:58] &lt;lykos&gt; lykos seemed to be in possession of a mysterious totem...
Sun 11-24 [18:31:58] &lt;lykos&gt; misha seems to be in possession of a mysterious totem...
Sun 11-24 [18:31:58] &lt;lykos&gt; sust seems to be in possession of 2 mysterious totems...
Sun 11-24 [18:31:58] &lt;lykos&gt; zoid seems to be in possession of a mysterious totem...
Sun 11-24 [18:31:58] &lt;lykos&gt; The villagers must now vote for whom to lynch. Use "!lynch &lt;nick&gt;" to cast your vote. 5 votes are required to lynch.
Sun 11-24 [18:32:04] &lt;misha&gt; !v Ramona 
Sun 11-24 [18:32:04] &lt;lykos&gt; misha votes for Ramona.
Sun 11-24 [18:32:04] &lt;sust&gt; ono
Sun 11-24 [18:32:06] &lt;dax&gt; !lynch Ramona 
Sun 11-24 [18:32:06] &lt;lykos&gt; dax votes for Ramona.
Sun 11-24 [18:32:10] &lt;hexa-&gt; hungry
Sun 11-24 [18:32:10] &lt;sust&gt; !v ram
Sun 11-24 [18:32:10] &lt;lykos&gt; sust votes for Ramona.
Sun 11-24 [18:32:12] &lt;Faely&gt; !v ram
Sun 11-24 [18:32:12] &lt;lykos&gt; Faely votes for Ramona.
Sun 11-24 [18:32:12] &lt;lykos&gt; zoid impatiently votes for Ramona.
Sun 11-24 [18:32:12] &lt;lykos&gt; The tribe has decided to exile Ramona, a wolf shaman. They do not make it far into the snowstorm before the cold consumes them.
Sun 11-24 [18:32:12] * lykos removes voice from Ramona
Sun 11-24 [18:32:13] &lt;lykos&gt; Day lasted 00:13. It is now nighttime. All players check for PMs from me for instructions. If you did not receive one, simply sit back, relax, and wait patiently for morning.
Sun 11-24 [18:32:13] &lt;lykos&gt; The tribe is hungry and needs to be fed 2 times tonight. They have gone hungry 1 time in the past.
Sun 11-24 [18:32:13] &lt;hexa-&gt; !v ramona
Sun 11-24 [18:32:16] &lt;jacob1&gt; great
Sun 11-24 [18:32:19] &lt;dax&gt; who needs feeding
Sun 11-24 [18:32:20] &lt;hexa-&gt; me
Sun 11-24 [18:32:23] &lt;zoid&gt; wait, what?
Sun 11-24 [18:32:23] &lt;hexa-&gt; have pacifism 
Sun 11-24 [18:32:25] &lt;Faely&gt; I have revealing
Sun 11-24 [18:32:26] &lt;zoid&gt; I'm hungry
Sun 11-24 [18:32:26] &lt;jacob1&gt; me too
Sun 11-24 [18:32:27] &lt;sust&gt; i got retrib
Sun 11-24 [18:32:29] &lt;jacob1&gt; from yesterday
Sun 11-24 [18:32:31] &lt;zoid&gt; I also have pacifism.
Sun 11-24 [18:32:35] &lt;misha&gt; sust: don't say who you're going to give it to
Sun 11-24 [18:32:38] &lt;nyuszika7h&gt; ok
Sun 11-24 [18:32:39] &lt;misha&gt; pick whoever you feel like VG might haunt
Sun 11-24 [18:32:39] &lt;jacob1&gt; oh, feeding self
Sun 11-24 [18:32:43] &lt;jacob1&gt; don't feed me then
Sun 11-24 [18:32:47] &lt;nyuszika7h&gt; who should I DT hmm
Sun 11-24 [18:32:48] &lt;sust&gt; oh
Sun 11-24 [18:32:49] &lt;Faely&gt; can't feed
Sun 11-24 [18:32:50] &lt;sust&gt; i'm also silenced
Sun 11-24 [18:32:54] &lt;dax&gt; hexa-: how are you not dead if you were hungry and got no totems since you said you were hungry
Sun 11-24 [18:32:56] &lt;sust&gt; so i can't give it out
Sun 11-24 [18:32:58] &lt;hexa-&gt; dax: idk
Sun 11-24 [18:33:01] &lt;misha&gt; i think sometimes you get two nights
Sun 11-24 [18:33:05] &lt;misha&gt; depending on how hungry you were the first time
Sun 11-24 [18:33:10] &lt;misha&gt; message is the same for 1 night and 2 nights, i think
Sun 11-24 [18:33:12] &lt;hexa-&gt; yep, two nights now
Sun 11-24 [18:33:41] &lt;lykos&gt; A few villagers awake early and notice it is still dark outside. The night is almost over and there are still whispers heard in the village.
Sun 11-24 [18:33:56] &lt;hexa-&gt; nyu pacified
Sun 11-24 [18:34:12] &lt;lykos&gt; Night lasted 02:00. It is now daytime. The villagers awake, thankful for surviving the night, and search the village... 
Sun 11-24 [18:34:12] &lt;lykos&gt; The tribe was not fed enough last night and looks increasingly on-edge from their hunger.
Sun 11-24 [18:34:12] &lt;lykos&gt; The night is over, but the storm still rages outside. The tribe elder estimates the storm will subside in 2 more days.
Sun 11-24 [18:34:12] &lt;lykos&gt; The dead body of sust, a vengeful ghost, is found. Those remaining mourn the tragedy.
Sun 11-24 [18:34:12] &lt;lykos&gt; The dead body of zoid, a vengeful ghost, is found. Those remaining mourn the tragedy.
Sun 11-24 [18:34:12] &lt;lykos&gt; The dead body of nyuszika7h, a vengeful ghost, is found. Those remaining mourn the tragedy.
Sun 11-24 [18:34:12] &lt;lykos&gt; The dead body of hexa-, a vengeful ghost, is found. Those remaining mourn the tragedy.
Sun 11-24 [18:34:12] * lykos removes voice from sust nyuszika7h hexa- zoid
Sun 11-24 [18:34:12] &lt;lykos&gt; hexa- seemed to be in possession of 2 mysterious totems...
Sun 11-24 [18:34:12] &lt;lykos&gt; jacob1 seems to be in possession of a mysterious totem...
Sun 11-24 [18:34:12] &lt;lykos&gt; lykos seemed to be in possession of a mysterious totem...
Sun 11-24 [18:34:12] &lt;lykos&gt; misha seems to be in possession of 2 mysterious totems...
Sun 11-24 [18:34:12] &lt;lykos&gt; nyuszika7h seemed to be in possession of a mysterious totem...
Sun 11-24 [18:34:12] &lt;lykos&gt; sust seemed to be in possession of a mysterious totem...
Sun 11-24 [18:34:12] &lt;lykos&gt; zoid seemed to be in possession of a mysterious totem...
Sun 11-24 [18:34:12] &lt;lykos&gt; Game over! The evil spirits have demolished the tribe, and the remaining wolf shamans travel to other clans to spread their misery there.
Sun 11-24 [18:34:12] &lt;lykos&gt; Game lasted 10:12. 01:09 was day. 09:02 was night. 
Sun 11-24 [18:34:12] &lt;lykos&gt; The wolf shamans were Ramona, Faely, and jacob1. The shamans were misha, aismallard, rdococ, and dax. The vengeful ghosts were sust (was shaman), nyuszika7h (shaman), el (shaman), hexa- (shaman), and zoid (shaman).
Sun 11-24 [18:34:15] &lt;lykos&gt; The winners are Faely, Ramona, el, hexa-, jacob1, nyuszika7h, sust, and zoid.
Sun 11-24 [18:34:15] * lykos sets mode -m ##werewolf
Sun 11-24 [18:34:15] * lykos removes voice from jacob1 dax Faely
Sun 11-24 [18:34:15] * lykos removes voice from misha

**Comment by nyuszika7h** [comment]
I like this bug
