### ISSUE TITLE
Wolf overpowered remaining villager, but nobody wins

### ISSUE THREAD

**Issue by mweinelt** [lykoss/lykos#419]
We just played 5p def and the game ended with one wolf overpowering one villager. But the turnout was that nobody won the game.

```
14:06 <@lykos> Game over! There are the same number of wolves as uninjured villagers. The wolves overpower the villagers and win.
[...]
14:06 <@lykos> Nobody wins.
```

<details><summary>Complete game log</summary>
<pre>
14:01 <@lykos> gqrter543, bobfasul, RandomRaven, hexa-, and simplexish: Welcome to Werewolf, the popular detective/social party game (a theme of Mafia). Using the default game mode.
14:01 ℹ  Mode ##werewolf [+m] by lykos
14:01 <@lykos> It is now nighttime. All players check for PMs from me for instructions.
14:02 <+gqrter543> sv
14:02 <+hexa-> villaging simplexish
14:02 <+bobfasul> hv
14:02 <+simplexish> hv
14:02 <+RandomRaven> )bobv
14:02 <+bobfasul> bobv
14:02 <@lykos> Night lasted 00:49. It is now daytime. The villagers awake, thankful for surviving the night, and search the village...
14:02 <@lykos> The dead body of bobfasul, a villager, is found. Those remaining mourn the tragedy.
14:02 ℹ  Mode ##werewolf [-v bobfasul] by lykos
14:02 <@lykos> The villagers must now vote for whom to lynch. Use "!lynch <nick>" to cast your vote. 3 votes are required to lynch.
14:03 <+hexa-> so many villagers seen
14:03 <+gqrter543> !v RandomRaven
14:03 <@lykos> gqrter543 votes for RandomRaven.
14:03 <+hexa-> aha?
14:04 <+gqrter543> !r
14:04 <@lykos> gqrter543's vote was retracted.
14:04 <+hexa-> ok, I'm seer
14:04 <+RandomRaven> Ok, hi wolf
14:04 <+hexa-> anyone going to counter me?
14:04 <+RandomRaven> I am seer
14:04 <+RandomRaven> I saw who hexa- killed
14:04 <+hexa-> this is awkward
14:04 <+RandomRaven> !v hexa-
14:04 <@lykos> RandomRaven votes for hexa-.
14:05 <+hexa-> RandomRaven: wait a  second
14:05 <+hexa-> !v simplexish
14:05 <@lykos> hexa- votes for simplexish.
14:05 <+hexa-> let's go that route
14:05 <+gqrter543> nope
14:05 <+gqrter543> it's either hexa or RandomRaven
14:05 <+hexa-> gqrter543: how so?
14:05 <+gqrter543> !v hexa-
14:05 <@lykos> gqrter543 votes for hexa-.
14:05 <+simplexish> !v hexa-
14:05 <@lykos> simplexish votes for hexa-.
14:05 <@lykos> The villagers tie up hexa- and throw them into the lake. It seems that a villager doesn't float too well.
14:05 ℹ  Mode ##werewolf [-v hexa-] by lykos
14:05 <@lykos> Day lasted 02:38. It is now nighttime. All players check for PMs from me for instructions. If you did not receive one, simply sit back, relax, and wait patiently for morning.
14:05 <+simplexish> :3
14:06 <+simplexish> RandomRaven, see someone, pls
14:06 <+gqrter543> why would a villager pretend to be seer?
14:06 <@lykos> Night lasted 00:58. It is now daytime. The villagers awake, thankful for surviving the night, and search the village...
14:06 <@lykos> The dead body of RandomRaven, a seer, is found. Those remaining mourn the tragedy.
14:06 ℹ  Mode ##werewolf [-v RandomRaven] by lykos
14:06 <@lykos> Game over! There are the same number of wolves as uninjured villagers. The wolves overpower the villagers and win.
14:06 <@lykos> Game lasted 04:25. 02:38 was day. 01:47 was night.
14:06 <@lykos> The wolf was simplexish. The seer was RandomRaven. The villagers were gqrter543, hexa-, and bobfasul.
14:06 <@lykos> Nobody wins.
14:06 ℹ  Mode ##werewolf [-mvv gqrter543 simplexish] by lykos
</pre>
</details>

**Comment by jacob1** [comment]
That's really strange. Potentially relevant is that you did /cycle before the game started:

Wed 03-18 [08:59:03] * simplexish has left ##werewolf ("Leaving")
Wed 03-18 [08:59:03] <lykos> simplexish ate some poisonous berries and has died. New player count: 4
Wed 03-18 [08:59:06] * simplexish has joined ##werewolf
Wed 03-18 [08:59:09] <simplexish> !j
Wed 03-18 [08:59:09] <lykos> simplexish has stumbled upon the village after a night of sleepwalking. They raised the number of players to 5.

**Comment by mweinelt** [comment]
I'm hexa, not simplexish. But good catch!
