### ISSUE TITLE
don't give night idling warnings to people who got exchanged that night

### ISSUE THREAD

**Issue by MishaCatskill** [lykoss/lykos#427]
being exchanged suddenly changes your situation without warning, which is confusing and requires you to take some time to figure out what to do since your old plans don't apply anymore. at the same time, you have limited time to decide because you only get whatever fraction of the night timeout is left when the exchange triggers. people should do their best to act anyway, but sometimes they're not going to manage it in time and I don't think it's fair to give them autowarnings if they mess up under those circumstances.

**Comment by mweinelt** [comment]
You are just getting switched without info on how to act, you need to know that by heart which isn't entirely reasonable. Also you don't get to see who's on your team.

```
03:46 <lykos> You are a villager. It is your job to lynch all of the wolves.
03:53 <lykos> You are now a werecrow.
03:53 <hexa-> oh hi
03:53 <hexa-> !stats
03:53 <lykos> 5 players: simplexish, RyanKnack, hexa- (werecrow), Sora, and noomy (cursed)
03:53 <lykos> It is currently night. There are no wolves, 1 werecrow, no wolf cubs, 0-1 traitors, no detectives, no harlots, no matchmakers, no seers, no shamans, 1 crazed shaman, and 2-3 villagers.
03:54 <hexa-> !time
03:54 <lykos> There is 01:02 remaining until sunrise.
03:54 <hexa-> kill sora
03:54 <lykos> You have selected Sora to be killed.
03:54 <lykos> You have not yet acted with all of your roles tonight. Please read the messages sent to you at beginning of night and ensure that you have successfully used every command you are able to use.
03:54 <hexa-> observe sim
03:54 <lykos> You transform into a large crow and start your flight to simplexish's house. You will return after collecting your observations when day begins.
03:54 <lykos> As the sun rises, you conclude that simplexish was sleeping all night long, and you fly back to your house.
```

**Comment by MishaCatskill** [comment]
Any other role change that happens during the night, such as a cub or traitor becoming a full wolf due to another wolf getting idlekilled at night, should also be treated the same as exchange and not give out automated penalties. Depending on the exact timing it might be nearly impossible to act in time, and is always unexpected and confusing.
