### ISSUE TITLE
Perform and/or Mode config options

### ISSUE THREAD

**Issue by trobotham** [lykoss/lykos#435]
It would be ideal to have a perform and/or mode config option, the reason for this is because we have a auth line which makes the bot flood exempt on a network that we run it on but it also requires a usermode to be set by the client/bot.

This would also be useful for other common ircd-side modes such as +B which marks the user as a bot on several IRCds.

**Comment by skizzerz** [comment]
This is a great suggestion, would probably implement it as a list of commands to run on connect (run after all the usual registration stuff is complete but before joining any channels).

In the meantime, a bot owner can use `!fsend` to manually send such commands; would need to be done each time the bot starts.
