### ISSUE TITLE
Wild child doesn't turn when idol idles out

### ISSUE THREAD

**Issue by an-empty-string** [lykoss/lykos#437]
In a game on 19th April 2020 starting at 23:55 UTC, I was wild child and idolized `noomy`:

```
23:55 -- lykos: You are a wild child. You must pick an idol with "choose <nick>", and you will become a wolf if your idol dies. You are a villager as long as your idol is alive.
23:55 -- lykos: Players: erry, aismallard, Quokka, nyuszika7h, neemos, Mariven, hexa-, Tux[Qyou], Iciloo, RyanKnack, werekitten, and noomy
23:55 <empty_string> choose noomy
23:55 -- lykos: You have picked noomy to be your idol for this game.
```

Then, at midnight 20th April:

```
00:00 <@lykos> noomy didn't get out of bed for a very long time and has been found dead. The survivors bury the wolf's body.
```

However, I didn't get any messages from lykos about turning, and didn't get any messages in wolfchat. I think this is a bug; according to wiki, "once their idol dies for any reason, they become a wolf" and this would seem to include idling out.

**Comment by jacob1** [comment]
Seems intentional, but I'm unsure why.

https://github.com/lykoss/lykos/commit/e163fec80ad7cbfa8980c819921473376d1b7ff5

Clone turns when the target idles out, so I don't see why wild child shouldn't either

**Comment by MishaCatskill** [comment]
This should definitely behave like clone and not like lovers.

**Comment by skizzerz** [comment]
Clone is wrong here, not wild child. Probably clone shouldn't turn if the target idles out, but should be able to pick a new target instead. Someone idling out is not supposed to trigger _anything_ on death.

**Comment by MishaCatskill** [comment]
I'd be fine with both clone and wild child getting to retarget if their original selection idles out.
