### ISSUE TITLE
!swap after quitting IRC doesn't stop reaper from killing player

### ISSUE THREAD

**Issue by nyuszika7h** [lykoss/lykos#438]
```
04/26 00:58:52 <-- Tux[Qyou] (~TuxQyou]@unaffiliated/tux-qyou/x-4822048) has quit (Read error: Connection reset by peer)
04/26 00:58:52 <@lykos> Tux[Qyou] has gone missing.
04/26 00:58:56 <+auror> I--
04/26 00:58:58 <+nyuszika7h> pls
04/26 00:59:02 <+auror> omg
04/26 00:59:07 <+Quokka> auror was taxudo assassin ?
04/26 00:59:09 <+Quokka> ...
04/26 00:59:11 <+auror> Quokka no
04/26 00:59:12 -- Mode ##werewolf [+v taxudo] by lykos
04/26 00:59:13 <@lykos> taxudo has swapped places with Tux[Qyou].
04/26 00:59:25 <+taxudo> :D
04/26 01:00:00 <@lykos> taxudo was mauled by wild animals and has died. It seems that villager meat is tasty.
04/26 01:00:00 -- Mode ##werewolf [-v taxudo] by lykos
```

Tux[Qyou] and taxudo were both in the channel already (same host and account). Tux[Qyou] quit, then taxudo did a !swap, but he was still killed by reaper a minute later.

**Comment by jacob1** [comment]
Going to copy paste my own issue here:

During a game today, my connection crashed again. I immediately did !swap from my alternate connection, but found myself unable to vote. I didn't attempt any other channel or PM commands during this time. Eventually I was removed from the game by the reaper.

The connection I did the !swap on had been in the channel for a long period of time. It was identified to the same account, with the same hostmask, only difference is that the ident was jacob1 vs. ~jacob1.

Notes from moonmoon:
Sat 06-06 [20:04:21] basically your new connection was somehow in users._ghosts
Sat 06-06 [20:04:29] and people in that set are completely ignored by lykos
Sat 06-06 [20:04:44] so somehow your join or swap didn't remove you from it

Here's some logs, may be mildly helpful:

Sat 06-06 [19:39:13] * jacob1 (jacob1@Powder/Developer/lykos.jacob1) has quit (Remote host closed the connection)
Sat 06-06 [19:39:13] jacob1 has gone missing.

In pm:
Sat 06-06 [19:39:20] swap
Sat 06-06 [19:39:21] You are a succubus.

Back in channel:
Sat 06-06 [19:39:20] * lykos gives voice to mooo
Sat 06-06 [19:39:21] mooo has swapped places with jacob1.

Unable to vote. 60 seconds after the original crash, an idle out happens:
Sat 06-06 [19:40:18] mooo was mauled by wild animals and has died. It seems that succubus meat is tasty.
