### ISSUE TITLE
Pestilence totem doesn't work

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#439]
Revealroles output from night N:
<lykos> werecrow: ZFC | wolf cub: spookly | assassin: misha | detective: no-n | matchmaker: misha | shaman: RyanKnack (has 1 protection totem) | sharpshooter: RyanKnack (0 bullets) | villager: culey, empty_string | crazed shaman: moonmoon (has 1 pestilence totem)

Day N:
&lt;lykos> RyanKnack was attacked last night, but their totem emitted a brilliant flash of light, blinding the attacker and allowing them to escape.
&lt;lykos> RyanKnack seems to be in possession of a mysterious totem...
&lt;lykos> no-n seems to be in possession of a mysterious totem...

no-n clearly got the pestilence totem here. RyanKnack got the prot.

Revealroles output from night N+1:
&lt;lykos> werecrow: ZFC | assassin: misha (targeting empty_string) | detective: no-n | matchmaker: misha | shaman: RyanKnack (has 1 protection totem) | sharpshooter: RyanKnack (0 bullets) | villager: culey, empty_string | crazed shaman: moonmoon (has 1 pestilence totem)

Wolf cub was lynched. And by chance, both shaman got the same totems again. But that's not relevant. The relevant bit is who died next:

Day N+1:
&lt;lykos> The dead body of RyanKnack, a shaman, is found. Those remaining mourn the tragedy.
&lt;lykos> The dead body of no-n, a detective, is found. Those remaining mourn the tragedy.
&lt;lykos> empty_string seems to be in possession of a mysterious totem...
&lt;lykos> misha seems to be in possession of a mysterious totem...

no-n is dead here, meaning wolves should be ill and unable to kill the next night. But in fact, empty_string dies:

&lt;lykos> The dead body of empty_string, a villager, is found. Those remaining mourn the tragedy.

**Comment by skizzerz** [comment]
Fixed in 4ce7fb31160a84d73ca26d28cc1457dbaff51986
