### ISSUE TITLE
Detectiv id command both result

### ISSUE THREAD

**Issue by svdermant** [lykoss/lykos#458]
Is it possible to set the detective so that the roles are revealed on both sides with the command id. That means private for the detective himself and for the public in the channel?

The following concern.

Werewolf is similar to Mafia. There is a detective in both games.

When the detective at mafia checks a citizen, the result is sent privately to the detective himself and also to the room itself for all citizens.

Is it somehow possible to do the same for your detectives for werewolf?

If so, what do I have to change? Note I am not an expert in the Python programming language, I also do not have the necessary IQ. It would be nice if you can help me what exactly needs to be changed.

**Comment by skizzerz** [comment]
I have never seen a variant of mafia where the detective's results are public for everyone. In any case, this is not something we support doing, and we will not add support for it either.

The detective may choose to reveal themselves to the village and claim who they identified (of course, the other villagers don't have to believe them, and the wolves may try to convince the village that they are lying about being detective). This also has the downside of the detective likely dying the next night, so they need to be careful about when they reveal themselves (if ever) and how they go about sharing information.

If you really want to go about this, you'd need to code your own custom role. This requires a both pretty good understanding of how the bot's code is put together and a decent working knowledge of Python, as custom roles are among the most difficult things to do in the bot. You can look at the existing detective.py file for inspiration on this, as it will be largely identical to what you're after, however.

**Comment by svdermant** [comment]
You have never played mafia where this is the case? hmm no good

Here I have a source of a German mafia game:

https://knuddels-wiki.de/index.php/Detektiv

**Comment by svdermant** [comment]
look Official description. it shouldn't be a must. it was just an idea or a question.
