### ISSUE TITLE
Bot accepts some commands only in --debug mode

### ISSUE THREAD

**Issue by svdermant** [lykoss/lykos#459]
Hello from my german.json I have changed various commands. or German added.
Some like! Fjoin or! Fjoin <number>

If he only accepts in debug mode, if he runs normally he does not react to it.
Did I not pay attention to something
here is the part with the commands:

    "_commands": {
        "*": "For assistance in configuring this section, please see https://werewolf.chat/Translation#Commands",
        "": [""],
        "abstain": ["verzichten", "vz", "keinlynch", "kl", "keinevote", "kv", "abstain", "abs", "nolynch", "nl", "novote", "nv"],
        "admins": ["admins", "ops"],
        "bite": ["beißen", "bite"],
        "bless": ["segne", "bless"],
        "cat": ["katze", "cat"],
        "charm": ["bezaubern", "charm"],
        "choose": ["wähle", "choose"],
        "clone": ["kopiere", "clone"],
        "coin": ["münze", "coin"],
        "consecrate": ["weihe", "consecrate"],
        "curse": ["verfluche", "curse"],
        "deadchat": ["todeschat", "deadchat"],
        "eval": ["eval"],
        "exec": ["exec"],
        "faftergame": ["fnachspiel", "nachspiel", "faftergame", "aftergame"],
        "fday": ["ftag", "fday"],
        "fdie": ["fdie", "fbye"],
        "fdo": ["fmessage", "fdo", "fme"],
        "fflags": ["fflags"],
        "fgame": ["fspiel", "fgame"],
        "fgoat": ["fziege", "fgoat"],
        "fjoin": ["fbeitritt", "fjoin"],
        "flastgame": ["fletztesspiel", "letztesspiel", "flastgame", "lastgame"],
        "fleave": ["fverlassen", "fleave", "fquit"],
        "fnight": ["fnacht", "fnight"],
        "force": ["force"],
        "fpull": ["fbotupdate", "fpull", "pull"],
        "freceive": ["fempfangen", "freceive"],
        "frestart": ["fneustart", "frestart", "restart"],
        "frole": ["frolle", "frole"],
        "fsay": ["fsage", "fsay"],
        "fsend": ["fsenden", "fsend"],
        "fspectate": ["fspectate"],
        "fstart": ["fstarten", "fstart"],
        "fstasis": ["fspielsperre", "fstasis"],
        "fstop": ["fstop"],
        "ftemplate": ["ftemplate", "template"],
        "ftotem": ["ftotem"],
        "fwait": ["fwarten", "fwait"],
        "fwarn": ["fwarn"],
        "game": ["spiel", "game"],
        "games": ["varianten", "Spiele", "games", "modes"],
        "gamestats": ["spielstats", "gamestats", "gstats"],
        "goat": ["ziege", "goat"],
        "guard": ["schutz", "guard", "protect", "save"],
        "help": ["hilfe", "help"],
        "hex": ["verhex", "hex"],
        "id": ["suchen", "id", "investigate"],
        "immunize": ["geben", "impfe", "give", "immunize", "immunise"],
        "join": ["mm", "join", "j"],
        "kill": ["töte", "kill"],
        "latency": ["latenz", "latency"],
        "leave": ["verlassen", "vl", "leave", "quit", "q"],
        "lynch": ["galgen", "lynch"],
        "match": ["verkupple", "match", "choose"],
        "myrole": ["meinerolle", "myrole"],
        "mystats": ["meinestats", "ms", "mystats", "m"],
        "notice": ["notice"],
        "observe": ["observieren", "observe"],
        "pass": ["aussetzen", "pass"],
        "ping": ["ping"],
        "pingif": ["pingif", "pingme", "pingat", "pingpref"],
        "playerstats": ["ss", "spielerstats", "playerstats", "pstats", "player", "p"],
        "pony": ["pferd", "pony", "horse"],
        "pray": ["beten", "pray"],
        "refreshdb": ["dbrefresh", "refreshdb"],
        "retract": ["zurück", "retract", "r"],
        "revealroles": ["rollendebug", "revealroles"],
        "rforce": ["rforce"],
        "roles": ["rollen", "roles"],
        "rolestats": ["rollenstats", "rolestats", "rstats"],
        "rules": ["regeln", "rules"],
        "see" : ["sehen", "see"],
        "setdisplay": ["setzeanzeige", "setdisplay"],
        "shoot": ["schießen", "shoot"],
        "side": ["überlaufen", "side"],
        "spectate": ["beobachte", "spectate"],
        "start": ["start"],
        "stasis": ["sperre", "stasis"],
        "stats": ["statistik", "spieler", "stats", "players"],
        "swap": ["ersetze", "swap", "replace"],
        "sync": ["sync", "fsync"],
        "target": ["ziel", "target"],
        "time": ["zeit", "time", "t"],
        "totem": ["totemgeben", "give", "totem"],
        "update": ["aktualisieren", "update"],
        "visit": ["besuche", "visit"],
        "vote": ["stimme", "vote", "v"],
        "votes": ["stimmen", "votes"],
        "wait": ["warten", "wait", "w"],
        "warn": ["warn"],
        "whoami": ["whoami"],
        "wiki": ["wiki"],

        "north": ["norden", "north", "n"],
        "east": ["osten", "o", "east", "e"],
        "south": ["süden", "south", "s"],
        "west": ["westen", "west", "w"],
        "feed": ["füttern", "feed"],

        "leave opt force": ["-force", "--force"],

        "warn ack": ["ack"],
        "warn add": ["hinzufügen", "add"],
        "warn del": ["löschen", "del"],
        "warn help": ["hilfe", "help"],
        "warn list": ["liste", "list"],
        "warn set": ["setze", "set"],
        "warn view": ["anzeigen", "view"],
        "warn opt account": ["-nickname", "-account", "--account", "-A"],
        "warn opt all": ["-alle", "-all", "--all", "-a"],
        "warn opt ban": ["-ban", "--ban", "-b"],
        "warn opt deny": ["-verbieten", "-deny", "--deny", "-d"],
        "warn opt expires": ["-ablauf", "-expires", "--expires", "-e"],
        "warn opt help": ["-hilfe", "-help", "--help", "-h", "-?"],
        "warn opt notes": ["-notizen", "-notes", "--notes", "-n"],
        "warn opt reason": ["-grund", "-reason", "--reason", "-r"],
        "warn opt stasis": ["-sperre", "-stasis", "--stasis", "-s"],

whats wrong?
https://pastebin.com/xPAqHnu8
With the Pastebin link you can see the display from the terminal putty once in debug mode where the commands are reacted to and once in normal mode where nothing happens.

https://pastebin.com/xPAqHnu8

**Comment by nyuszika7h** [comment]
This is by design. Admins are not supposed to be able to mess with a normal game by joining fake players, changing roles, etc. That's what debug mode is for.
