### ISSUE TITLE
Bot starts with errors he has logged. How can i fix this?

### ISSUE THREAD

**Issue by svdermant** [lykoss/lykos#471]
Hello and Goood day @ all It's been a long time since I updated the game on my german network. Today I did it and the bot starts with errors that it logged. How can I fix this?
Here is the Error.log: https://pastebin.com/Xnfdy3Bc

I don't know if it has anything to do with the German translation. I started months ago, I once included the german.json.

[german.zip](https://github.com/lykoss/lykos/files/6736955/german.zip)
extract the zip file to see the content.

Thx for help.

**Comment by Vgr255** [comment]
This has been fixed in e033507
