### ISSUE TITLE
Roles are not properly casefolded

### ISSUE THREAD

**Issue by svdermant** [lykoss/lykos#474]
Hello I found a problem with my German translation and the pray command for the Prophet.

The following:
if I have the following in my translation in the area: _roles:
 "wolf": ["Wolf", "Wölfe"],

Then the bot tells me as a prophet that this role does not exist although several fakenicks have this role.
However, I write everything in small letters:

 "wolf": ["wolf", "wölfe"],

Then the Pray command works, but wolf is written in lower case in the endgame statistics.

Meanwhile, Wolf is written in the German language with a capital W.

I can write all roles in lower case so that the pray command works, but then many German players would say wolf or priest etc is capitalized etc and would assume I would not speak the german language etc

[german.zip](https://github.com/lykoss/lykos/files/6758654/german.zip)

You are welcome to check this yourself.

I was told to post this eventual bug on github.

**Comment by Vgr255** [comment]
This is indeed a bug due to how we handle roles. For now, you will need to keep everything lowercase. We will fix this eventually.

**Comment by svdermant** [comment]
I thank you I hope this happens as soon as possible,
