### ISSUE TITLE
Seer/hunter doesn't get player list in PM

### ISSUE THREAD

**Issue by jacob1** [lykoss/lykos#482]
pony and tris reported a bug where seer doesn't get player list. Tris also reported it as hunter.

I can also confirm the bug as hunter, I only received this PM each night:
Sun 10-31 [00:50:18] <lykos> You are a hunter. Once per game, you may kill another player with "kill <nick>". If you do not wish to kill anyone tonight, use "pass" instead.

Does not happen as wolf.

**Comment by skizzerz** [comment]
Fixed in 3b3870c9f365944134225c5b7364430c5bce0158
