### ISSUE TITLE
lykos always responds in notices to commands issued in channel if the user isn't joined

### ISSUE THREAD

**Issue by wctaiwan** [lykoss/lykos#491]
e.g. if someone isn't joined but says !time, lykos would respond privately in a notice message instead of in channel. This is somewhat jarring, and in many cases the information is actually broadly useful, for example if people are trying to see if there's enough time left for a game to form before deciding whether to join.

**Comment by MishaCatskill** [comment]
see also #483 (same problem but in night phase, now fixed)

**Comment by wctaiwan** [comment]
Will reopen #483 instead.
