### ISSUE TITLE
!gstats counts Fool wins and Fool wins separately

### ISSUE THREAD

**Issue by fndax** [lykoss/lykos#509]
```
02:40:33 <+me> !gstats foolish 8
02:40:33 <@lykos> 8 player games (foolish) | Villager wins: 123 (37%), Wolf wins: 135 (41%), Fool wins: 69 (21%), Fool wins: 2 (1%), Total games: 329
```

I assume the way lykos stores stats in the db for the fool team changed at some point or something, idk.

**Comment by skizzerz** [comment]
Should be fixed now (no code changes needed, the database just had some old records that needed to get mapped over to the new-ish way of doing things)
