### ISSUE TITLE
Make mad scientist skip over dead people

### ISSUE THREAD

**Issue by skizzerz** [lykoss/lykos#55]
Let's say join order is A B C D and B is scientist. If C dies night 1 and B is lynched, this would change it so that both A and D would die as well instead of just A.

Should be configurable, both by an on/off switch as well as a number of players based on how large game was started at (as skipping over dead people is OP in small games, but needed in larger ones).

**Comment by jacob1** [comment]
a setting was added a while ago in b82cc92997b310ff7fd78133df39798f03430f49
