### ISSUE TITLE
Can we add another idled out death line?

### ISSUE THREAD

**Issue by ChiyoOsaka** [lykoss/lykos#60]
An example idle-out-death-line is:

> \<lykos\> Makiavel didn't get out of bed for a very long time and has been found dead. The survivors bury the villager's body.

Could we add:

> \<lykos\> $name became infected with the idle virus. Sadly, they did not respond to treatment and subsequently died.

**Comment by jacob1** [comment]
if someone wants to add this, then I guess that is ok. Closing the issue though because it is old, also I would prefer to stick to one message.
