### ISSUE TITLE
Werekitten?

### ISSUE THREAD

**Issue by ChiyoOsaka** [lykoss/lykos#70]
So, ~~erry~~ bcode, but still giving credit to erry suggested the idea of a werekitten. Now while I can't think of a role where this could be in use, but I did think that:

* A werekitten is something you randomly got as a wolf cub so instead of it appearing as "wolf cub" it would appear as "were kitten", but it's the same role.

* A preference you could set. Again, it's not a new role, but it would give you the label of "werekitten" every time you got the wolf cub role.

Thoughts?

**Comment by skizzerz** [comment]
Added werekitten in d00c15e
