### ISSUE TITLE
Require two people to start

### ISSUE THREAD

**Issue by tannn** [lykoss/lykos#9]
A suggestion discussing in ##werewolf is requiring two people to start a game. This would prevent an individual from starting the game prematurely, which is fairly common if they were unaware the other players were waiting for a larger number for more roles. It would also allow for more people to be ready to play the game when it begins, instead of someone starting the game when other people are afk.

**Comment by skizzerz** [comment]
Revisiting this, as there are a lot of grumbles about ninjastarters and something like this would be far more ideal than simply !fdenying start to everyone who "ninjastarts." Is this something that we still want to do?

 * The main issue with ninjastarting is people starting at low player counts after a large game just finished. As such, I don't think a threshold (where 2p are required only if the game is > N players) is a good idea.
 * The opposite of the above (and suggested above) of requiring more people to start the more players are in the game I also do not believe is a good idea, as it will imo lead to longer starting delays which may just end up outright canceling a game for hitting the hour time limit. Two starters I think should be fine regardless of game size.
 * If someone !joins or !quits after the first !start has been issued, do we reset the start count back to 0 or still count it (so the next !start starts even though conditions have changed). I'm leaning towards the former.

**Comment by tannn** [comment]
I agree that there should always be two people to start and the process should reset if someone joins or quits after the first !start. 

However, I do not believe this would always stop ninjastarters, since after one !start, someone else is sure to follow and !start as well.

**Comment by nyuszika7h** [comment]
> The opposite of the above (and suggested above) of requiring more people to start the more players are in the game I also do not believe is a good idea, as it will imo lead to longer starting delays which may just end up outright canceling a game for hitting the hour time limit.

I don't understand. If not enough people start, that means people are inactive, so cancelling the game is the right thing to do...?

**Comment by lutoma** [comment]
I believe this has been fixed 99460a36
